DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS subagents;
DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS lifecycle_events;
DROP TABLE IF EXISTS container_versions;
DROP TABLE IF EXISTS snapshots;
DROP TABLE IF EXISTS containers;
DROP TABLE IF EXISTS channel_sessions;
DROP TABLE IF EXISTS contact_channels;
DROP TABLE IF EXISTS bot_preauth_keys;
DROP TABLE IF EXISTS bot_channel_configs;
DROP TABLE IF EXISTS user_channel_bindings;
DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS bot_model_configs;
DROP TABLE IF EXISTS bot_settings;
DROP TABLE IF EXISTS bot_members;
DROP TABLE IF EXISTS contact_bind_tokens;
DROP TABLE IF EXISTS bots;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS contacts;
-- DROP TABLE IF EXISTS model_variants;
-- DROP TABLE IF EXISTS models;
-- DROP TABLE IF EXISTS llm_providers;
DROP TYPE IF EXISTS user_role;
