// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBotNetworkConfig = `-- name: GetBotNetworkConfig :one
SELECT
  network_enabled,
  network_provider,
  network_config
FROM bots
WHERE id = $1
`

type GetBotNetworkConfigRow struct {
	NetworkEnabled  bool   `json:"network_enabled"`
	NetworkProvider string `json:"network_provider"`
	NetworkConfig   []byte `json:"network_config"`
}

func (q *Queries) GetBotNetworkConfig(ctx context.Context, id pgtype.UUID) (GetBotNetworkConfigRow, error) {
	row := q.db.QueryRow(ctx, getBotNetworkConfig, id)
	var i GetBotNetworkConfigRow
	err := row.Scan(&i.NetworkEnabled, &i.NetworkProvider, &i.NetworkConfig)
	return i, err
}
