// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: iam.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addSSOGroupMembership = `-- name: AddSSOGroupMembership :exec
INSERT OR IGNORE INTO iam_group_members (user_id, group_id, source, provider_id)
VALUES (?1, ?2, 'sso', ?3)
`

type AddSSOGroupMembershipParams struct {
	UserID     string         `json:"user_id"`
	GroupID    string         `json:"group_id"`
	ProviderID sql.NullString `json:"provider_id"`
}

func (q *Queries) AddSSOGroupMembership(ctx context.Context, arg AddSSOGroupMembershipParams) error {
	_, err := q.db.ExecContext(ctx, addSSOGroupMembership, arg.UserID, arg.GroupID, arg.ProviderID)
	return err
}

const assignPrincipalRole = `-- name: AssignPrincipalRole :one
INSERT INTO iam_principal_roles (
  id, principal_type, principal_id, role_id, resource_type, resource_id, source, provider_id
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
ON CONFLICT DO NOTHING
RETURNING id, principal_type, principal_id, role_id, resource_type, resource_id, source, provider_id, created_at, updated_at
`

type AssignPrincipalRoleParams struct {
	PrincipalType string         `json:"principal_type"`
	PrincipalID   string         `json:"principal_id"`
	RoleID        string         `json:"role_id"`
	ResourceType  string         `json:"resource_type"`
	ResourceID    sql.NullString `json:"resource_id"`
	Source        string         `json:"source"`
	ProviderID    sql.NullString `json:"provider_id"`
}

func (q *Queries) AssignPrincipalRole(ctx context.Context, arg AssignPrincipalRoleParams) (IamPrincipalRole, error) {
	row := q.db.QueryRowContext(ctx, assignPrincipalRole,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.RoleID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Source,
		arg.ProviderID,
	)
	var i IamPrincipalRole
	err := row.Scan(
		&i.ID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.RoleID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Source,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearSSOGroupMemberships = `-- name: ClearSSOGroupMemberships :exec
DELETE FROM iam_group_members
WHERE user_id = ?1
  AND source = 'sso'
  AND provider_id = ?2
`

type ClearSSOGroupMembershipsParams struct {
	UserID     string         `json:"user_id"`
	ProviderID sql.NullString `json:"provider_id"`
}

func (q *Queries) ClearSSOGroupMemberships(ctx context.Context, arg ClearSSOGroupMembershipsParams) error {
	_, err := q.db.ExecContext(ctx, clearSSOGroupMemberships, arg.UserID, arg.ProviderID)
	return err
}

const createIAMLoginCode = `-- name: CreateIAMLoginCode :one
INSERT INTO iam_login_codes (id, code_hash, user_id, identity_id, session_id, expires_at)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1, ?2, ?3, ?4, ?5
)
RETURNING id, code_hash, user_id, identity_id, session_id, expires_at, used_at, created_at
`

type CreateIAMLoginCodeParams struct {
	CodeHash   string         `json:"code_hash"`
	UserID     string         `json:"user_id"`
	IdentityID sql.NullString `json:"identity_id"`
	SessionID  string         `json:"session_id"`
	ExpiresAt  string         `json:"expires_at"`
}

func (q *Queries) CreateIAMLoginCode(ctx context.Context, arg CreateIAMLoginCodeParams) (IamLoginCode, error) {
	row := q.db.QueryRowContext(ctx, createIAMLoginCode,
		arg.CodeHash,
		arg.UserID,
		arg.IdentityID,
		arg.SessionID,
		arg.ExpiresAt,
	)
	var i IamLoginCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.IdentityID,
		&i.SessionID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createIAMSession = `-- name: CreateIAMSession :one
INSERT INTO iam_sessions (id, user_id, identity_id, expires_at, ip_address, user_agent, metadata)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1, ?2, ?3, ?4, ?5, ?6
)
RETURNING id, user_id, identity_id, issued_at, expires_at, revoked_at, ip_address, user_agent, metadata, created_at, updated_at
`

type CreateIAMSessionParams struct {
	UserID     string         `json:"user_id"`
	IdentityID sql.NullString `json:"identity_id"`
	ExpiresAt  string         `json:"expires_at"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	Metadata   string         `json:"metadata"`
}

func (q *Queries) CreateIAMSession(ctx context.Context, arg CreateIAMSessionParams) (IamSession, error) {
	row := q.db.QueryRowContext(ctx, createIAMSession,
		arg.UserID,
		arg.IdentityID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i IamSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdentityID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordIdentity = `-- name: CreatePasswordIdentity :one
INSERT INTO iam_identities (
  id, user_id, provider_type, provider_id, subject, credential_secret, email, username,
  display_name, avatar_url, raw_claims
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1, 'password', NULL, lower(?2), ?3,
  ?4, ?5, ?6, ?7, '{}'
)
ON CONFLICT DO UPDATE SET
  credential_secret = EXCLUDED.credential_secret,
  email = EXCLUDED.email,
  username = EXCLUDED.username,
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, provider_type, provider_id, subject, credential_secret, email, username, display_name, avatar_url, raw_claims, last_login_at, created_at, updated_at
`

type CreatePasswordIdentityParams struct {
	UserID           string         `json:"user_id"`
	Subject          string         `json:"subject"`
	CredentialSecret sql.NullString `json:"credential_secret"`
	Email            sql.NullString `json:"email"`
	Username         sql.NullString `json:"username"`
	DisplayName      sql.NullString `json:"display_name"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreatePasswordIdentity(ctx context.Context, arg CreatePasswordIdentityParams) (IamIdentity, error) {
	row := q.db.QueryRowContext(ctx, createPasswordIdentity,
		arg.UserID,
		arg.Subject,
		arg.CredentialSecret,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i IamIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderID,
		&i.Subject,
		&i.CredentialSecret,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawClaims,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIAMGroup = `-- name: DeleteIAMGroup :exec
DELETE FROM iam_groups
WHERE id = ?1
`

func (q *Queries) DeleteIAMGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIAMGroup, id)
	return err
}

const deleteIAMGroupMember = `-- name: DeleteIAMGroupMember :exec
DELETE FROM iam_group_members
WHERE user_id = ?1
  AND group_id = ?2
`

type DeleteIAMGroupMemberParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) DeleteIAMGroupMember(ctx context.Context, arg DeleteIAMGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteIAMGroupMember, arg.UserID, arg.GroupID)
	return err
}

const deletePrincipalRole = `-- name: DeletePrincipalRole :exec
DELETE FROM iam_principal_roles
WHERE id = ?1
`

func (q *Queries) DeletePrincipalRole(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePrincipalRole, id)
	return err
}

const deletePrincipalRoleAssignment = `-- name: DeletePrincipalRoleAssignment :exec
DELETE FROM iam_principal_roles
WHERE principal_type = ?1
  AND principal_id = ?2
  AND resource_type = ?3
  AND resource_id = ?4
  AND role_id = (
    SELECT id FROM iam_roles WHERE key = ?5
  )
`

type DeletePrincipalRoleAssignmentParams struct {
	PrincipalType string         `json:"principal_type"`
	PrincipalID   string         `json:"principal_id"`
	ResourceType  string         `json:"resource_type"`
	ResourceID    sql.NullString `json:"resource_id"`
	RoleKey       string         `json:"role_key"`
}

func (q *Queries) DeletePrincipalRoleAssignment(ctx context.Context, arg DeletePrincipalRoleAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, deletePrincipalRoleAssignment,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.ResourceType,
		arg.ResourceID,
		arg.RoleKey,
	)
	return err
}

const deleteSSOGroupMapping = `-- name: DeleteSSOGroupMapping :exec
DELETE FROM iam_sso_group_mappings
WHERE provider_id = ?1
  AND external_group = ?2
`

type DeleteSSOGroupMappingParams struct {
	ProviderID    string `json:"provider_id"`
	ExternalGroup string `json:"external_group"`
}

func (q *Queries) DeleteSSOGroupMapping(ctx context.Context, arg DeleteSSOGroupMappingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSSOGroupMapping, arg.ProviderID, arg.ExternalGroup)
	return err
}

const deleteSSOProvider = `-- name: DeleteSSOProvider :exec
DELETE FROM iam_sso_providers WHERE id = ?1
`

func (q *Queries) DeleteSSOProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSSOProvider, id)
	return err
}

const extendIAMSession = `-- name: ExtendIAMSession :one
UPDATE iam_sessions
SET expires_at = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND revoked_at IS NULL
RETURNING id, user_id, identity_id, issued_at, expires_at, revoked_at, ip_address, user_agent, metadata, created_at, updated_at
`

type ExtendIAMSessionParams struct {
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
}

func (q *Queries) ExtendIAMSession(ctx context.Context, arg ExtendIAMSessionParams) (IamSession, error) {
	row := q.db.QueryRowContext(ctx, extendIAMSession, arg.ExpiresAt, arg.ID)
	var i IamSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdentityID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIAMGroupByID = `-- name: GetIAMGroupByID :one
SELECT id, "key", display_name, source, external_id, metadata, created_at, updated_at
FROM iam_groups
WHERE id = ?1
`

func (q *Queries) GetIAMGroupByID(ctx context.Context, id string) (IamGroup, error) {
	row := q.db.QueryRowContext(ctx, getIAMGroupByID, id)
	var i IamGroup
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Source,
		&i.ExternalID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIAMSessionByID = `-- name: GetIAMSessionByID :one
SELECT s.id, s.user_id, s.identity_id, s.issued_at, s.expires_at, s.revoked_at, s.ip_address, s.user_agent, s.metadata, s.created_at, s.updated_at, u.is_active AS user_is_active
FROM iam_sessions s
JOIN iam_users u ON u.id = s.user_id
WHERE s.id = ?1
`

type GetIAMSessionByIDRow struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	IdentityID   sql.NullString `json:"identity_id"`
	IssuedAt     string         `json:"issued_at"`
	ExpiresAt    string         `json:"expires_at"`
	RevokedAt    sql.NullString `json:"revoked_at"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	Metadata     string         `json:"metadata"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	UserIsActive int64          `json:"user_is_active"`
}

func (q *Queries) GetIAMSessionByID(ctx context.Context, id string) (GetIAMSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIAMSessionByID, id)
	var i GetIAMSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdentityID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserIsActive,
	)
	return i, err
}

const getIdentityByProviderSubject = `-- name: GetIdentityByProviderSubject :one
SELECT id, user_id, provider_type, provider_id, subject, credential_secret, email, username, display_name, avatar_url, raw_claims, last_login_at, created_at, updated_at
FROM iam_identities
WHERE provider_type = ?1
  AND COALESCE(provider_id, '') = COALESCE(?2, '')
  AND subject = ?3
`

type GetIdentityByProviderSubjectParams struct {
	ProviderType string         `json:"provider_type"`
	ProviderID   sql.NullString `json:"provider_id"`
	Subject      string         `json:"subject"`
}

func (q *Queries) GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (IamIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByProviderSubject, arg.ProviderType, arg.ProviderID, arg.Subject)
	var i IamIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderID,
		&i.Subject,
		&i.CredentialSecret,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawClaims,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordIdentityBySubject = `-- name: GetPasswordIdentityBySubject :one
SELECT id, user_id, provider_type, provider_id, subject, credential_secret, email, username, display_name, avatar_url, raw_claims, last_login_at, created_at, updated_at
FROM iam_identities
WHERE provider_type = 'password'
  AND subject = lower(?1)
`

func (q *Queries) GetPasswordIdentityBySubject(ctx context.Context, subject string) (IamIdentity, error) {
	row := q.db.QueryRowContext(ctx, getPasswordIdentityBySubject, subject)
	var i IamIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderID,
		&i.Subject,
		&i.CredentialSecret,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawClaims,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByKey = `-- name: GetRoleByKey :one
SELECT id, "key", scope, description, is_system, created_at, updated_at
FROM iam_roles
WHERE key = ?1
`

func (q *Queries) GetRoleByKey(ctx context.Context, key string) (IamRole, error) {
	row := q.db.QueryRowContext(ctx, getRoleByKey, key)
	var i IamRole
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Scope,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOProviderByID = `-- name: GetSSOProviderByID :one
SELECT id, type, "key", name, enabled, config, attribute_mapping, jit_enabled, email_linking_policy, trust_email, created_at, updated_at
FROM iam_sso_providers
WHERE id = ?1
`

func (q *Queries) GetSSOProviderByID(ctx context.Context, id string) (IamSsoProvider, error) {
	row := q.db.QueryRowContext(ctx, getSSOProviderByID, id)
	var i IamSsoProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Key,
		&i.Name,
		&i.Enabled,
		&i.Config,
		&i.AttributeMapping,
		&i.JitEnabled,
		&i.EmailLinkingPolicy,
		&i.TrustEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOProviderByKey = `-- name: GetSSOProviderByKey :one
SELECT id, type, "key", name, enabled, config, attribute_mapping, jit_enabled, email_linking_policy, trust_email, created_at, updated_at
FROM iam_sso_providers
WHERE key = ?1
`

func (q *Queries) GetSSOProviderByKey(ctx context.Context, key string) (IamSsoProvider, error) {
	row := q.db.QueryRowContext(ctx, getSSOProviderByKey, key)
	var i IamSsoProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Key,
		&i.Name,
		&i.Enabled,
		&i.Config,
		&i.AttributeMapping,
		&i.JitEnabled,
		&i.EmailLinkingPolicy,
		&i.TrustEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
  SELECT 1
  FROM iam_principal_roles pr
  JOIN iam_roles r ON r.id = pr.role_id
  JOIN iam_role_permissions rp ON rp.role_id = r.id
  JOIN iam_permissions p ON p.id = rp.permission_id
  WHERE p.key = ?1
    AND pr.resource_type = ?2
    AND (pr.resource_id = ?3 OR pr.resource_id IS NULL)
    AND (
      (pr.principal_type = 'user' AND pr.principal_id = ?4)
      OR (
        pr.principal_type = 'group'
        AND pr.principal_id IN (
          SELECT group_id FROM iam_group_members WHERE user_id = ?4
        )
      )
    )
) AS allowed
`

type HasPermissionParams struct {
	PermissionKey string         `json:"permission_key"`
	ResourceType  string         `json:"resource_type"`
	ResourceID    sql.NullString `json:"resource_id"`
	UserID        string         `json:"user_id"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasPermission,
		arg.PermissionKey,
		arg.ResourceType,
		arg.ResourceID,
		arg.UserID,
	)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listEnabledSSOProviders = `-- name: ListEnabledSSOProviders :many
SELECT id, type, "key", name, enabled, config, attribute_mapping, jit_enabled, email_linking_policy, trust_email, created_at, updated_at
FROM iam_sso_providers
WHERE enabled = 1
ORDER BY name ASC
`

func (q *Queries) ListEnabledSSOProviders(ctx context.Context) ([]IamSsoProvider, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamSsoProvider
	for rows.Next() {
		var i IamSsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Key,
			&i.Name,
			&i.Enabled,
			&i.Config,
			&i.AttributeMapping,
			&i.JitEnabled,
			&i.EmailLinkingPolicy,
			&i.TrustEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIAMGroupMembers = `-- name: ListIAMGroupMembers :many
SELECT gm.user_id, gm.group_id, gm.source, gm.provider_id, gm.created_at, gm.updated_at, u.username, u.email, u.display_name
FROM iam_group_members gm
JOIN iam_users u ON u.id = gm.user_id
WHERE gm.group_id = ?1
ORDER BY u.username ASC, u.email ASC
`

type ListIAMGroupMembersRow struct {
	UserID      string         `json:"user_id"`
	GroupID     string         `json:"group_id"`
	Source      string         `json:"source"`
	ProviderID  sql.NullString `json:"provider_id"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	Username    sql.NullString `json:"username"`
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) ListIAMGroupMembers(ctx context.Context, groupID string) ([]ListIAMGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listIAMGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIAMGroupMembersRow
	for rows.Next() {
		var i ListIAMGroupMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.Source,
			&i.ProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIAMGroups = `-- name: ListIAMGroups :many
SELECT id, "key", display_name, source, external_id, metadata, created_at, updated_at
FROM iam_groups
ORDER BY key ASC
`

func (q *Queries) ListIAMGroups(ctx context.Context) ([]IamGroup, error) {
	rows, err := q.db.QueryContext(ctx, listIAMGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamGroup
	for rows.Next() {
		var i IamGroup
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.Source,
			&i.ExternalID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalRoles = `-- name: ListPrincipalRoles :many
SELECT
  pr.id, pr.principal_type, pr.principal_id, pr.role_id, pr.resource_type, pr.resource_id, pr.source, pr.provider_id, pr.created_at, pr.updated_at,
  r.key AS role_key,
  r.scope AS role_scope,
  u.username AS user_username,
  u.email AS user_email,
  u.display_name AS user_display_name,
  g.key AS group_key,
  g.display_name AS group_display_name
FROM iam_principal_roles pr
JOIN iam_roles r ON r.id = pr.role_id
LEFT JOIN iam_users u ON pr.principal_type = 'user' AND u.id = pr.principal_id
LEFT JOIN iam_groups g ON pr.principal_type = 'group' AND g.id = pr.principal_id
WHERE pr.resource_type = ?1
  AND COALESCE(pr.resource_id, '') = COALESCE(?2, '')
ORDER BY r.key ASC, pr.principal_type ASC, user_username ASC, group_key ASC
`

type ListPrincipalRolesParams struct {
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
}

type ListPrincipalRolesRow struct {
	ID               string         `json:"id"`
	PrincipalType    string         `json:"principal_type"`
	PrincipalID      string         `json:"principal_id"`
	RoleID           string         `json:"role_id"`
	ResourceType     string         `json:"resource_type"`
	ResourceID       sql.NullString `json:"resource_id"`
	Source           string         `json:"source"`
	ProviderID       sql.NullString `json:"provider_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	RoleKey          string         `json:"role_key"`
	RoleScope        string         `json:"role_scope"`
	UserUsername     sql.NullString `json:"user_username"`
	UserEmail        sql.NullString `json:"user_email"`
	UserDisplayName  sql.NullString `json:"user_display_name"`
	GroupKey         sql.NullString `json:"group_key"`
	GroupDisplayName sql.NullString `json:"group_display_name"`
}

func (q *Queries) ListPrincipalRoles(ctx context.Context, arg ListPrincipalRolesParams) ([]ListPrincipalRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipalRoles, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrincipalRolesRow
	for rows.Next() {
		var i ListPrincipalRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.RoleID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Source,
			&i.ProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleKey,
			&i.RoleScope,
			&i.UserUsername,
			&i.UserEmail,
			&i.UserDisplayName,
			&i.GroupKey,
			&i.GroupDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, "key", scope, description, is_system, created_at, updated_at
FROM iam_roles
ORDER BY scope ASC, key ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]IamRole, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamRole
	for rows.Next() {
		var i IamRole
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Scope,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSOGroupMappingsByProvider = `-- name: ListSSOGroupMappingsByProvider :many
SELECT m.id, m.provider_id, m.external_group, m.group_id, m.created_at, m.updated_at, g.key AS group_key, g.display_name AS group_display_name
FROM iam_sso_group_mappings m
JOIN iam_groups g ON g.id = m.group_id
WHERE m.provider_id = ?1
ORDER BY m.external_group ASC
`

type ListSSOGroupMappingsByProviderRow struct {
	ID               string `json:"id"`
	ProviderID       string `json:"provider_id"`
	ExternalGroup    string `json:"external_group"`
	GroupID          string `json:"group_id"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	GroupKey         string `json:"group_key"`
	GroupDisplayName string `json:"group_display_name"`
}

func (q *Queries) ListSSOGroupMappingsByProvider(ctx context.Context, providerID string) ([]ListSSOGroupMappingsByProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, listSSOGroupMappingsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSSOGroupMappingsByProviderRow
	for rows.Next() {
		var i ListSSOGroupMappingsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ExternalGroup,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupKey,
			&i.GroupDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSOProviders = `-- name: ListSSOProviders :many
SELECT id, type, "key", name, enabled, config, attribute_mapping, jit_enabled, email_linking_policy, trust_email, created_at, updated_at
FROM iam_sso_providers
ORDER BY created_at DESC
`

func (q *Queries) ListSSOProviders(ctx context.Context) ([]IamSsoProvider, error) {
	rows, err := q.db.QueryContext(ctx, listSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamSsoProvider
	for rows.Next() {
		var i IamSsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Key,
			&i.Name,
			&i.Enabled,
			&i.Config,
			&i.AttributeMapping,
			&i.JitEnabled,
			&i.EmailLinkingPolicy,
			&i.TrustEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeIAMSession = `-- name: RevokeIAMSession :exec
UPDATE iam_sessions
SET revoked_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeIAMSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeIAMSession, id)
	return err
}

const updateIdentityLastLogin = `-- name: UpdateIdentityLastLogin :exec
UPDATE iam_identities
SET last_login_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) UpdateIdentityLastLogin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateIdentityLastLogin, id)
	return err
}

const upsertExternalIdentity = `-- name: UpsertExternalIdentity :one
INSERT INTO iam_identities (
  id, user_id, provider_type, provider_id, subject, email, username, display_name, avatar_url, raw_claims
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8, ?9
)
ON CONFLICT DO UPDATE SET
  user_id = EXCLUDED.user_id,
  email = EXCLUDED.email,
  username = EXCLUDED.username,
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  raw_claims = EXCLUDED.raw_claims,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, provider_type, provider_id, subject, credential_secret, email, username, display_name, avatar_url, raw_claims, last_login_at, created_at, updated_at
`

type UpsertExternalIdentityParams struct {
	UserID       string         `json:"user_id"`
	ProviderType string         `json:"provider_type"`
	ProviderID   sql.NullString `json:"provider_id"`
	Subject      string         `json:"subject"`
	Email        sql.NullString `json:"email"`
	Username     sql.NullString `json:"username"`
	DisplayName  sql.NullString `json:"display_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	RawClaims    string         `json:"raw_claims"`
}

func (q *Queries) UpsertExternalIdentity(ctx context.Context, arg UpsertExternalIdentityParams) (IamIdentity, error) {
	row := q.db.QueryRowContext(ctx, upsertExternalIdentity,
		arg.UserID,
		arg.ProviderType,
		arg.ProviderID,
		arg.Subject,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.RawClaims,
	)
	var i IamIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderID,
		&i.Subject,
		&i.CredentialSecret,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.RawClaims,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIAMGroup = `-- name: UpsertIAMGroup :one
INSERT INTO iam_groups (id, key, display_name, source, external_id, metadata)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  source = EXCLUDED.source,
  external_id = EXCLUDED.external_id,
  metadata = EXCLUDED.metadata,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, "key", display_name, source, external_id, metadata, created_at, updated_at
`

type UpsertIAMGroupParams struct {
	ID          string         `json:"id"`
	Key         string         `json:"key"`
	DisplayName string         `json:"display_name"`
	Source      string         `json:"source"`
	ExternalID  sql.NullString `json:"external_id"`
	Metadata    string         `json:"metadata"`
}

func (q *Queries) UpsertIAMGroup(ctx context.Context, arg UpsertIAMGroupParams) (IamGroup, error) {
	row := q.db.QueryRowContext(ctx, upsertIAMGroup,
		arg.ID,
		arg.Key,
		arg.DisplayName,
		arg.Source,
		arg.ExternalID,
		arg.Metadata,
	)
	var i IamGroup
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.Source,
		&i.ExternalID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIAMGroupMember = `-- name: UpsertIAMGroupMember :one
INSERT INTO iam_group_members (user_id, group_id, source, provider_id)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (user_id, group_id, source, provider_id) DO UPDATE SET
  updated_at = CURRENT_TIMESTAMP
RETURNING user_id, group_id, source, provider_id, created_at, updated_at
`

type UpsertIAMGroupMemberParams struct {
	UserID     string         `json:"user_id"`
	GroupID    string         `json:"group_id"`
	Source     string         `json:"source"`
	ProviderID sql.NullString `json:"provider_id"`
}

func (q *Queries) UpsertIAMGroupMember(ctx context.Context, arg UpsertIAMGroupMemberParams) (IamGroupMember, error) {
	row := q.db.QueryRowContext(ctx, upsertIAMGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.Source,
		arg.ProviderID,
	)
	var i IamGroupMember
	err := row.Scan(
		&i.UserID,
		&i.GroupID,
		&i.Source,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSSOGroupMapping = `-- name: UpsertSSOGroupMapping :one
INSERT INTO iam_sso_group_mappings (id, provider_id, external_group, group_id)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1, ?2, ?3
)
ON CONFLICT (provider_id, external_group) DO UPDATE SET
  group_id = EXCLUDED.group_id,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, provider_id, external_group, group_id, created_at, updated_at
`

type UpsertSSOGroupMappingParams struct {
	ProviderID    string `json:"provider_id"`
	ExternalGroup string `json:"external_group"`
	GroupID       string `json:"group_id"`
}

func (q *Queries) UpsertSSOGroupMapping(ctx context.Context, arg UpsertSSOGroupMappingParams) (IamSsoGroupMapping, error) {
	row := q.db.QueryRowContext(ctx, upsertSSOGroupMapping, arg.ProviderID, arg.ExternalGroup, arg.GroupID)
	var i IamSsoGroupMapping
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ExternalGroup,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSSOProvider = `-- name: UpsertSSOProvider :one
INSERT INTO iam_sso_providers (
  id, type, key, name, enabled, config, attribute_mapping, jit_enabled, email_linking_policy, trust_email
)
VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6,
  ?7, ?8, ?9, ?10
)
ON CONFLICT (key) DO UPDATE SET
  type = EXCLUDED.type,
  name = EXCLUDED.name,
  enabled = EXCLUDED.enabled,
  config = EXCLUDED.config,
  attribute_mapping = EXCLUDED.attribute_mapping,
  jit_enabled = EXCLUDED.jit_enabled,
  email_linking_policy = EXCLUDED.email_linking_policy,
  trust_email = EXCLUDED.trust_email,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, type, "key", name, enabled, config, attribute_mapping, jit_enabled, email_linking_policy, trust_email, created_at, updated_at
`

type UpsertSSOProviderParams struct {
	ID                 string `json:"id"`
	Type               string `json:"type"`
	Key                string `json:"key"`
	Name               string `json:"name"`
	Enabled            int64  `json:"enabled"`
	Config             string `json:"config"`
	AttributeMapping   string `json:"attribute_mapping"`
	JitEnabled         int64  `json:"jit_enabled"`
	EmailLinkingPolicy string `json:"email_linking_policy"`
	TrustEmail         int64  `json:"trust_email"`
}

func (q *Queries) UpsertSSOProvider(ctx context.Context, arg UpsertSSOProviderParams) (IamSsoProvider, error) {
	row := q.db.QueryRowContext(ctx, upsertSSOProvider,
		arg.ID,
		arg.Type,
		arg.Key,
		arg.Name,
		arg.Enabled,
		arg.Config,
		arg.AttributeMapping,
		arg.JitEnabled,
		arg.EmailLinkingPolicy,
		arg.TrustEmail,
	)
	var i IamSsoProvider
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Key,
		&i.Name,
		&i.Enabled,
		&i.Config,
		&i.AttributeMapping,
		&i.JitEnabled,
		&i.EmailLinkingPolicy,
		&i.TrustEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const useIAMLoginCode = `-- name: UseIAMLoginCode :one
UPDATE iam_login_codes
SET used_at = CURRENT_TIMESTAMP
WHERE code_hash = ?1
  AND used_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
RETURNING id, code_hash, user_id, identity_id, session_id, expires_at, used_at, created_at
`

func (q *Queries) UseIAMLoginCode(ctx context.Context, codeHash string) (IamLoginCode, error) {
	row := q.db.QueryRowContext(ctx, useIAMLoginCode, codeHash)
	var i IamLoginCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.IdentityID,
		&i.SessionID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
