// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_diagnostic_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRuntimeDiagnosticEvent = `-- name: CreateRuntimeDiagnosticEvent :one
INSERT INTO runtime_diagnostic_events (
  id,
  bot_id,
  scope,
  agent_id,
  session_id,
  runtime_id,
  phase,
  severity,
  code,
  message,
  metadata
) VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10
)
RETURNING id, bot_id, scope, agent_id, session_id, runtime_id, phase, severity, code, message, metadata, created_at
`

type CreateRuntimeDiagnosticEventParams struct {
	BotID     string         `json:"bot_id"`
	Scope     string         `json:"scope"`
	AgentID   string         `json:"agent_id"`
	SessionID sql.NullString `json:"session_id"`
	RuntimeID string         `json:"runtime_id"`
	Phase     string         `json:"phase"`
	Severity  string         `json:"severity"`
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	Metadata  string         `json:"metadata"`
}

func (q *Queries) CreateRuntimeDiagnosticEvent(ctx context.Context, arg CreateRuntimeDiagnosticEventParams) (RuntimeDiagnosticEvent, error) {
	row := q.db.QueryRowContext(ctx, createRuntimeDiagnosticEvent,
		arg.BotID,
		arg.Scope,
		arg.AgentID,
		arg.SessionID,
		arg.RuntimeID,
		arg.Phase,
		arg.Severity,
		arg.Code,
		arg.Message,
		arg.Metadata,
	)
	var i RuntimeDiagnosticEvent
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Scope,
		&i.AgentID,
		&i.SessionID,
		&i.RuntimeID,
		&i.Phase,
		&i.Severity,
		&i.Code,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRuntimeDiagnosticEventsBefore = `-- name: DeleteRuntimeDiagnosticEventsBefore :exec
DELETE FROM runtime_diagnostic_events
WHERE created_at < ?1
`

func (q *Queries) DeleteRuntimeDiagnosticEventsBefore(ctx context.Context, before string) error {
	_, err := q.db.ExecContext(ctx, deleteRuntimeDiagnosticEventsBefore, before)
	return err
}

const listRuntimeDiagnosticEventBotIDs = `-- name: ListRuntimeDiagnosticEventBotIDs :many
SELECT DISTINCT bot_id
FROM runtime_diagnostic_events
`

func (q *Queries) ListRuntimeDiagnosticEventBotIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeDiagnosticEventBotIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_id string
		if err := rows.Scan(&bot_id); err != nil {
			return nil, err
		}
		items = append(items, bot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeDiagnosticEventsByBot = `-- name: ListRuntimeDiagnosticEventsByBot :many
SELECT id, bot_id, scope, agent_id, session_id, runtime_id, phase, severity, code, message, metadata, created_at
FROM runtime_diagnostic_events
WHERE bot_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?2
`

type ListRuntimeDiagnosticEventsByBotParams struct {
	BotID      string `json:"bot_id"`
	LimitCount int64  `json:"limit_count"`
}

func (q *Queries) ListRuntimeDiagnosticEventsByBot(ctx context.Context, arg ListRuntimeDiagnosticEventsByBotParams) ([]RuntimeDiagnosticEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeDiagnosticEventsByBot, arg.BotID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuntimeDiagnosticEvent
	for rows.Next() {
		var i RuntimeDiagnosticEvent
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Scope,
			&i.AgentID,
			&i.SessionID,
			&i.RuntimeID,
			&i.Phase,
			&i.Severity,
			&i.Code,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRuntimeDiagnosticEventsByBotLimit = `-- name: PruneRuntimeDiagnosticEventsByBotLimit :exec
DELETE FROM runtime_diagnostic_events
WHERE runtime_diagnostic_events.bot_id = ?1
  AND id NOT IN (
    SELECT id
    FROM runtime_diagnostic_events AS keep
    WHERE keep.bot_id = ?1
    ORDER BY created_at DESC, id DESC
    LIMIT ?2
  )
`

type PruneRuntimeDiagnosticEventsByBotLimitParams struct {
	BotID     string `json:"bot_id"`
	KeepCount int64  `json:"keep_count"`
}

func (q *Queries) PruneRuntimeDiagnosticEventsByBotLimit(ctx context.Context, arg PruneRuntimeDiagnosticEventsByBotLimitParams) error {
	_, err := q.db.ExecContext(ctx, pruneRuntimeDiagnosticEventsByBotLimit, arg.BotID, arg.KeepCount)
	return err
}
