// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot_workdirs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveBotWorkdir = `-- name: ArchiveBotWorkdir :one
UPDATE bot_workdirs
SET archived_at = now(), updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
  AND archived_at IS NULL
RETURNING id
`

type ArchiveBotWorkdirParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	WorkdirID pgtype.UUID `json:"workdir_id"`
}

func (q *Queries) ArchiveBotWorkdir(ctx context.Context, arg ArchiveBotWorkdirParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, archiveBotWorkdir, arg.BotID, arg.WorkdirID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createBotWorkdir = `-- name: CreateBotWorkdir :one
INSERT INTO bot_workdirs (
  bot_id, name, target_kind, remote_binding_id, path, created_by_user_id
)
VALUES (
  $1,
  $2,
  $3,
  $4::uuid,
  $5,
  $6::uuid
)
RETURNING id, team_id, bot_id, name, target_kind, remote_binding_id, path, created_by_user_id, archived_at, created_at, updated_at
`

type CreateBotWorkdirParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	Name            string      `json:"name"`
	TargetKind      string      `json:"target_kind"`
	RemoteBindingID pgtype.UUID `json:"remote_binding_id"`
	Path            string      `json:"path"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateBotWorkdir(ctx context.Context, arg CreateBotWorkdirParams) (BotWorkdir, error) {
	row := q.db.QueryRow(ctx, createBotWorkdir,
		arg.BotID,
		arg.Name,
		arg.TargetKind,
		arg.RemoteBindingID,
		arg.Path,
		arg.CreatedByUserID,
	)
	var i BotWorkdir
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.Name,
		&i.TargetKind,
		&i.RemoteBindingID,
		&i.Path,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotWorkdir = `-- name: GetBotWorkdir :one
SELECT id, team_id, bot_id, name, target_kind, remote_binding_id, path, created_by_user_id, archived_at, created_at, updated_at
FROM bot_workdirs
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
`

type GetBotWorkdirParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	WorkdirID pgtype.UUID `json:"workdir_id"`
}

// Archived rows are returned on purpose: sessions bound to an archived
// workdir keep resolving their working directory; callers that must refuse
// archived workdirs (session creation) check archived_at themselves.
func (q *Queries) GetBotWorkdir(ctx context.Context, arg GetBotWorkdirParams) (BotWorkdir, error) {
	row := q.db.QueryRow(ctx, getBotWorkdir, arg.BotID, arg.WorkdirID)
	var i BotWorkdir
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.Name,
		&i.TargetKind,
		&i.RemoteBindingID,
		&i.Path,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotWorkdirs = `-- name: ListBotWorkdirs :many
SELECT id, team_id, bot_id, name, target_kind, remote_binding_id, path, created_by_user_id, archived_at, created_at, updated_at
FROM bot_workdirs
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND ($2::bool OR archived_at IS NULL)
ORDER BY created_at ASC, id ASC
`

type ListBotWorkdirsParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	IncludeArchived bool        `json:"include_archived"`
}

func (q *Queries) ListBotWorkdirs(ctx context.Context, arg ListBotWorkdirsParams) ([]BotWorkdir, error) {
	rows, err := q.db.Query(ctx, listBotWorkdirs, arg.BotID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotWorkdir
	for rows.Next() {
		var i BotWorkdir
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.Name,
			&i.TargetKind,
			&i.RemoteBindingID,
			&i.Path,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameBotWorkdir = `-- name: RenameBotWorkdir :one
UPDATE bot_workdirs
SET name = $1, updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND id = $3
  AND archived_at IS NULL
RETURNING id, team_id, bot_id, name, target_kind, remote_binding_id, path, created_by_user_id, archived_at, created_at, updated_at
`

type RenameBotWorkdirParams struct {
	Name      string      `json:"name"`
	BotID     pgtype.UUID `json:"bot_id"`
	WorkdirID pgtype.UUID `json:"workdir_id"`
}

func (q *Queries) RenameBotWorkdir(ctx context.Context, arg RenameBotWorkdirParams) (BotWorkdir, error) {
	row := q.db.QueryRow(ctx, renameBotWorkdir, arg.Name, arg.BotID, arg.WorkdirID)
	var i BotWorkdir
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.Name,
		&i.TargetKind,
		&i.RemoteBindingID,
		&i.Path,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
