// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (team_id, owner_user_id, name, display_name, avatar_url, timezone, is_active, metadata, status)
VALUES ($1::uuid, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type CreateBotParams struct {
	TeamID      pgtype.UUID `json:"team_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Name        string      `json:"name"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Timezone    pgtype.Text `json:"timezone"`
	IsActive    bool        `json:"is_active"`
	Metadata    []byte      `json:"metadata"`
	Status      string      `json:"status"`
}

type CreateBotRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (CreateBotRow, error) {
	row := q.db.QueryRow(ctx, createBot,
		arg.TeamID,
		arg.OwnerUserID,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.Metadata,
		arg.Status,
	)
	var i CreateBotRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotByID = `-- name: DeleteBotByID :exec
DELETE FROM bots
WHERE id = $1
  AND team_id = $2::uuid
`

type DeleteBotByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteBotByID(ctx context.Context, arg DeleteBotByIDParams) error {
	_, err := q.db.Exec(ctx, deleteBotByID, arg.ID, arg.TeamID)
	return err
}

const getBotByID = `-- name: GetBotByID :one
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, compaction_enabled, compaction_threshold, compaction_ratio, compaction_model_id, metadata, created_at, updated_at
FROM bots
WHERE id = $1
  AND team_id = $2::uuid
`

type GetBotByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

type GetBotByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerUserID         pgtype.UUID        `json:"owner_user_id"`
	Name                string             `json:"name"`
	DisplayName         pgtype.Text        `json:"display_name"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	Timezone            pgtype.Text        `json:"timezone"`
	IsActive            bool               `json:"is_active"`
	Status              string             `json:"status"`
	Language            string             `json:"language"`
	ReasoningEnabled    bool               `json:"reasoning_enabled"`
	ReasoningEffort     string             `json:"reasoning_effort"`
	ChatModelID         pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID    pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID    pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled    bool               `json:"heartbeat_enabled"`
	HeartbeatInterval   int32              `json:"heartbeat_interval"`
	HeartbeatPrompt     string             `json:"heartbeat_prompt"`
	CompactionEnabled   bool               `json:"compaction_enabled"`
	CompactionThreshold int32              `json:"compaction_threshold"`
	CompactionRatio     int32              `json:"compaction_ratio"`
	CompactionModelID   pgtype.UUID        `json:"compaction_model_id"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBotByID(ctx context.Context, arg GetBotByIDParams) (GetBotByIDRow, error) {
	row := q.db.QueryRow(ctx, getBotByID, arg.ID, arg.TeamID)
	var i GetBotByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.CompactionModelID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotByName = `-- name: GetBotByName :one
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, compaction_enabled, compaction_threshold, compaction_ratio, compaction_model_id, metadata, created_at, updated_at
FROM bots
WHERE team_id = $1::uuid
  AND name = $2
`

type GetBotByNameParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	Name   string      `json:"name"`
}

type GetBotByNameRow struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerUserID         pgtype.UUID        `json:"owner_user_id"`
	Name                string             `json:"name"`
	DisplayName         pgtype.Text        `json:"display_name"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	Timezone            pgtype.Text        `json:"timezone"`
	IsActive            bool               `json:"is_active"`
	Status              string             `json:"status"`
	Language            string             `json:"language"`
	ReasoningEnabled    bool               `json:"reasoning_enabled"`
	ReasoningEffort     string             `json:"reasoning_effort"`
	ChatModelID         pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID    pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID    pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled    bool               `json:"heartbeat_enabled"`
	HeartbeatInterval   int32              `json:"heartbeat_interval"`
	HeartbeatPrompt     string             `json:"heartbeat_prompt"`
	CompactionEnabled   bool               `json:"compaction_enabled"`
	CompactionThreshold int32              `json:"compaction_threshold"`
	CompactionRatio     int32              `json:"compaction_ratio"`
	CompactionModelID   pgtype.UUID        `json:"compaction_model_id"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBotByName(ctx context.Context, arg GetBotByNameParams) (GetBotByNameRow, error) {
	row := q.db.QueryRow(ctx, getBotByName, arg.TeamID, arg.Name)
	var i GetBotByNameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.CompactionModelID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessibleBots = `-- name: ListAccessibleBots :many
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
FROM bots b
WHERE b.team_id = $1::uuid
  AND (
    b.owner_user_id = $2
    OR EXISTS (
     SELECT 1 FROM bot_user_grants g
     WHERE g.bot_id = b.id
       AND g.team_id = $1::uuid
       AND (
         g.subject_type = 'everyone'
         OR (g.subject_type = 'user' AND g.user_id = $2)
       )
    )
  )
ORDER BY b.created_at DESC
`

type ListAccessibleBotsParams struct {
	TeamID      pgtype.UUID `json:"team_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

type ListAccessibleBotsRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccessibleBots(ctx context.Context, arg ListAccessibleBotsParams) ([]ListAccessibleBotsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleBots, arg.TeamID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleBotsRow
	for rows.Next() {
		var i ListAccessibleBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotsByOwner = `-- name: ListBotsByOwner :many
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
FROM bots
WHERE team_id = $1::uuid
  AND owner_user_id = $2
ORDER BY created_at DESC
`

type ListBotsByOwnerParams struct {
	TeamID      pgtype.UUID `json:"team_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

type ListBotsByOwnerRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListBotsByOwner(ctx context.Context, arg ListBotsByOwnerParams) ([]ListBotsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listBotsByOwner, arg.TeamID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotsByOwnerRow
	for rows.Next() {
		var i ListBotsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatEnabledBots = `-- name: ListHeartbeatEnabledBots :many
SELECT team_id, id, owner_user_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt
FROM bots
WHERE heartbeat_enabled = true
  AND status = 'ready'
`

type ListHeartbeatEnabledBotsRow struct {
	TeamID            pgtype.UUID `json:"team_id"`
	ID                pgtype.UUID `json:"id"`
	OwnerUserID       pgtype.UUID `json:"owner_user_id"`
	HeartbeatEnabled  bool        `json:"heartbeat_enabled"`
	HeartbeatInterval int32       `json:"heartbeat_interval"`
	HeartbeatPrompt   string      `json:"heartbeat_prompt"`
}

// Process-wide startup bootstrap: intentionally spans all teams (no team_id
// filter) so every team's heartbeat bots are scheduled after a restart. The
// selected team_id is threaded into each heartbeat job downstream.
func (q *Queries) ListHeartbeatEnabledBots(ctx context.Context) ([]ListHeartbeatEnabledBotsRow, error) {
	rows, err := q.db.Query(ctx, listHeartbeatEnabledBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeartbeatEnabledBotsRow
	for rows.Next() {
		var i ListHeartbeatEnabledBotsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.ID,
			&i.OwnerUserID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotOwner = `-- name: UpdateBotOwner :one
UPDATE bots
SET owner_user_id = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3::uuid
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type UpdateBotOwnerParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	ID          pgtype.UUID `json:"id"`
	TeamID      pgtype.UUID `json:"team_id"`
}

type UpdateBotOwnerRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBotOwner(ctx context.Context, arg UpdateBotOwnerParams) (UpdateBotOwnerRow, error) {
	row := q.db.QueryRow(ctx, updateBotOwner, arg.OwnerUserID, arg.ID, arg.TeamID)
	var i UpdateBotOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotProfile = `-- name: UpdateBotProfile :one
UPDATE bots
SET name = $1,
    display_name = $2,
    avatar_url = $3,
    timezone = $4,
    is_active = $5,
    metadata = $6,
    updated_at = now()
WHERE id = $7
  AND team_id = $8::uuid
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type UpdateBotProfileParams struct {
	Name        string      `json:"name"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Timezone    pgtype.Text `json:"timezone"`
	IsActive    bool        `json:"is_active"`
	Metadata    []byte      `json:"metadata"`
	ID          pgtype.UUID `json:"id"`
	TeamID      pgtype.UUID `json:"team_id"`
}

type UpdateBotProfileRow struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Name              string             `json:"name"`
	DisplayName       pgtype.Text        `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Timezone          pgtype.Text        `json:"timezone"`
	IsActive          bool               `json:"is_active"`
	Status            string             `json:"status"`
	Language          string             `json:"language"`
	ReasoningEnabled  bool               `json:"reasoning_enabled"`
	ReasoningEffort   string             `json:"reasoning_effort"`
	ChatModelID       pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID  pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID  pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled  bool               `json:"heartbeat_enabled"`
	HeartbeatInterval int32              `json:"heartbeat_interval"`
	HeartbeatPrompt   string             `json:"heartbeat_prompt"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBotProfile(ctx context.Context, arg UpdateBotProfileParams) (UpdateBotProfileRow, error) {
	row := q.db.QueryRow(ctx, updateBotProfile,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.Metadata,
		arg.ID,
		arg.TeamID,
	)
	var i UpdateBotProfileRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotStatus = `-- name: UpdateBotStatus :exec
UPDATE bots
SET status = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3::uuid
`

type UpdateBotStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) UpdateBotStatus(ctx context.Context, arg UpdateBotStatusParams) error {
	_, err := q.db.Exec(ctx, updateBotStatus, arg.Status, arg.ID, arg.TeamID)
	return err
}
