// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_identity_bindings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannelLinkCode = `-- name: CreateChannelLinkCode :one
INSERT INTO channel_link_codes (token, team_id, user_id, channel_type, expires_at)
VALUES ($1, $2, $3, $4::text, $5)
RETURNING token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at, team_id
`

type CreateChannelLinkCodeParams struct {
	Token       string             `json:"token"`
	TeamID      pgtype.UUID        `json:"team_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ChannelType pgtype.Text        `json:"channel_type"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateChannelLinkCode(ctx context.Context, arg CreateChannelLinkCodeParams) (ChannelLinkCode, error) {
	row := q.db.QueryRow(ctx, createChannelLinkCode,
		arg.Token,
		arg.TeamID,
		arg.UserID,
		arg.ChannelType,
		arg.ExpiresAt,
	)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const deleteUserChannelIdentityBinding = `-- name: DeleteUserChannelIdentityBinding :exec
DELETE FROM user_channel_identity_bindings
WHERE team_id = $1
  AND user_id = $2
  AND channel_identity_id = $3
`

type DeleteUserChannelIdentityBindingParams struct {
	TeamID            pgtype.UUID `json:"team_id"`
	UserID            pgtype.UUID `json:"user_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) DeleteUserChannelIdentityBinding(ctx context.Context, arg DeleteUserChannelIdentityBindingParams) error {
	_, err := q.db.Exec(ctx, deleteUserChannelIdentityBinding, arg.TeamID, arg.UserID, arg.ChannelIdentityID)
	return err
}

const getChannelLinkCodeByToken = `-- name: GetChannelLinkCodeByToken :one
SELECT token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at, team_id
FROM channel_link_codes
WHERE token = $1
  AND team_id = $2
`

type GetChannelLinkCodeByTokenParams struct {
	Token  string      `json:"token"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) GetChannelLinkCodeByToken(ctx context.Context, arg GetChannelLinkCodeByTokenParams) (ChannelLinkCode, error) {
	row := q.db.QueryRow(ctx, getChannelLinkCodeByToken, arg.Token, arg.TeamID)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const listChannelIdentityBindings = `-- name: ListChannelIdentityBindings :many
SELECT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id AND ci.team_id = b.team_id
WHERE b.team_id = $1
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	ChannelIdentityID          pgtype.UUID        `json:"channel_identity_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChannelType                pgtype.Text        `json:"channel_type"`
	ChannelSubjectID           pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   pgtype.Text        `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindings(ctx context.Context, teamID pgtype.UUID) ([]ListChannelIdentityBindingsRow, error) {
	rows, err := q.db.Query(ctx, listChannelIdentityBindings, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsRow
	for rows.Next() {
		var i ListChannelIdentityBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelIdentityBindingsForBot = `-- name: ListChannelIdentityBindingsForBot :many
SELECT DISTINCT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
INNER JOIN bots bot_scope ON bot_scope.id = $1
INNER JOIN bot_user_grants g ON g.user_id = b.user_id AND g.bot_id = bot_scope.id AND g.subject_type = 'user'
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id AND ci.team_id = b.team_id
WHERE b.team_id = bot_scope.team_id
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsForBotRow struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	ChannelIdentityID          pgtype.UUID        `json:"channel_identity_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChannelType                pgtype.Text        `json:"channel_type"`
	ChannelSubjectID           pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   pgtype.Text        `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindingsForBot(ctx context.Context, botID pgtype.UUID) ([]ListChannelIdentityBindingsForBotRow, error) {
	rows, err := q.db.Query(ctx, listChannelIdentityBindingsForBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsForBotRow
	for rows.Next() {
		var i ListChannelIdentityBindingsForBotRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelIdentityBindingsForUser = `-- name: ListChannelIdentityBindingsForUser :many
SELECT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id AND ci.team_id = b.team_id
WHERE b.team_id = $1
  AND b.user_id = $2
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsForUserParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type ListChannelIdentityBindingsForUserRow struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	ChannelIdentityID          pgtype.UUID        `json:"channel_identity_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChannelType                pgtype.Text        `json:"channel_type"`
	ChannelSubjectID           pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   pgtype.Text        `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindingsForUser(ctx context.Context, arg ListChannelIdentityBindingsForUserParams) ([]ListChannelIdentityBindingsForUserRow, error) {
	rows, err := q.db.Query(ctx, listChannelIdentityBindingsForUser, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsForUserRow
	for rows.Next() {
		var i ListChannelIdentityBindingsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByChannelIdentity = `-- name: ListUserIDsByChannelIdentity :many
SELECT user_id
FROM user_channel_identity_bindings
WHERE team_id = $1
  AND channel_identity_id = $2
`

type ListUserIDsByChannelIdentityParams struct {
	TeamID            pgtype.UUID `json:"team_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) ListUserIDsByChannelIdentity(ctx context.Context, arg ListUserIDsByChannelIdentityParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDsByChannelIdentity, arg.TeamID, arg.ChannelIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelLinkCodeConsumed = `-- name: MarkChannelLinkCodeConsumed :one
UPDATE channel_link_codes
SET consumed_at = now(),
    consumed_channel_identity_id = $1
WHERE token = $2
  AND team_id = $3
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at, team_id
`

type MarkChannelLinkCodeConsumedParams struct {
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
	Token             string      `json:"token"`
	TeamID            pgtype.UUID `json:"team_id"`
}

func (q *Queries) MarkChannelLinkCodeConsumed(ctx context.Context, arg MarkChannelLinkCodeConsumedParams) (ChannelLinkCode, error) {
	row := q.db.QueryRow(ctx, markChannelLinkCodeConsumed, arg.ChannelIdentityID, arg.Token, arg.TeamID)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const redeemChannelLinkCode = `-- name: RedeemChannelLinkCode :one
WITH identity_scope AS (
  SELECT ci.id, ci.team_id, ci.channel_type
  FROM channel_identities ci
  WHERE ci.id = $1
    AND ci.team_id = $2
),
claimed AS (
  UPDATE channel_link_codes c
  SET consumed_at = now(),
      consumed_channel_identity_id = (SELECT id FROM identity_scope)
  WHERE c.token = $3
    AND c.team_id = $2
    AND c.consumed_at IS NULL
    AND c.expires_at > now()
    AND EXISTS (
      SELECT 1
      FROM identity_scope i
      WHERE c.channel_type = '' OR c.channel_type = i.channel_type
    )
  RETURNING c.team_id, c.user_id, (SELECT id FROM identity_scope) AS channel_identity_id
)
INSERT INTO user_channel_identity_bindings (team_id, user_id, channel_identity_id)
SELECT team_id, user_id, channel_identity_id
FROM claimed
ON CONFLICT (team_id, user_id, channel_identity_id) DO UPDATE
  SET updated_at = now()
RETURNING id, user_id, channel_identity_id, created_at, updated_at, team_id
`

type RedeemChannelLinkCodeParams struct {
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
	TeamID            pgtype.UUID `json:"team_id"`
	Token             string      `json:"token"`
}

func (q *Queries) RedeemChannelLinkCode(ctx context.Context, arg RedeemChannelLinkCodeParams) (UserChannelIdentityBinding, error) {
	row := q.db.QueryRow(ctx, redeemChannelLinkCode, arg.ChannelIdentityID, arg.TeamID, arg.Token)
	var i UserChannelIdentityBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const upsertUserChannelIdentityBinding = `-- name: UpsertUserChannelIdentityBinding :one
INSERT INTO user_channel_identity_bindings (team_id, user_id, channel_identity_id)
SELECT $1, $2, ci.id
FROM channel_identities ci
WHERE ci.id = $3
  AND ci.team_id = $1
ON CONFLICT (team_id, user_id, channel_identity_id) DO UPDATE
  SET updated_at = now()
RETURNING id, user_id, channel_identity_id, created_at, updated_at, team_id
`

type UpsertUserChannelIdentityBindingParams struct {
	TeamID            pgtype.UUID `json:"team_id"`
	UserID            pgtype.UUID `json:"user_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) UpsertUserChannelIdentityBinding(ctx context.Context, arg UpsertUserChannelIdentityBindingParams) (UserChannelIdentityBinding, error) {
	row := q.db.QueryRow(ctx, upsertUserChannelIdentityBinding, arg.TeamID, arg.UserID, arg.ChannelIdentityID)
	var i UserChannelIdentityBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
