// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compaction_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeCompactionLog = `-- name: CompleteCompactionLog :one
UPDATE bot_history_message_compacts
SET status = $2,
    summary = $3,
    message_count = $4,
    error_message = $5,
    usage = $6,
    model_id = $7,
    coverage = $8,
    anchor_start_ms = $9,
    anchor_end_ms = $10,
    completed_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
          artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
          superseded_by, superseded_at, started_at, completed_at
`

type CompleteCompactionLogParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	Summary       string      `json:"summary"`
	MessageCount  int32       `json:"message_count"`
	ErrorMessage  string      `json:"error_message"`
	Usage         []byte      `json:"usage"`
	ModelID       pgtype.UUID `json:"model_id"`
	Coverage      []byte      `json:"coverage"`
	AnchorStartMs int64       `json:"anchor_start_ms"`
	AnchorEndMs   int64       `json:"anchor_end_ms"`
}

func (q *Queries) CompleteCompactionLog(ctx context.Context, arg CompleteCompactionLogParams) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRow(ctx, completeCompactionLog,
		arg.ID,
		arg.Status,
		arg.Summary,
		arg.MessageCount,
		arg.ErrorMessage,
		arg.Usage,
		arg.ModelID,
		arg.Coverage,
		arg.AnchorStartMs,
		arg.AnchorEndMs,
	)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.ArtifactVersion,
		&i.Coverage,
		&i.AnchorStartMs,
		&i.AnchorEndMs,
		&i.ArtifactLevel,
		&i.ParentIds,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCompactionLogsByBot = `-- name: CountCompactionLogsByBot :one
SELECT count(*) FROM bot_history_message_compacts WHERE bot_id = $1
`

func (q *Queries) CountCompactionLogsByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompactionLogsByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompactionLog = `-- name: CreateCompactionLog :one
INSERT INTO bot_history_message_compacts (bot_id, session_id)
VALUES ($1, $2)
RETURNING id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
          artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
          superseded_by, superseded_at, started_at, completed_at
`

type CreateCompactionLogParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) CreateCompactionLog(ctx context.Context, arg CreateCompactionLogParams) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRow(ctx, createCompactionLog, arg.BotID, arg.SessionID)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.ArtifactVersion,
		&i.Coverage,
		&i.AnchorStartMs,
		&i.AnchorEndMs,
		&i.ArtifactLevel,
		&i.ParentIds,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteCompactionLogsByBot = `-- name: DeleteCompactionLogsByBot :exec
DELETE FROM bot_history_message_compacts WHERE bot_id = $1
`

func (q *Queries) DeleteCompactionLogsByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompactionLogsByBot, botID)
	return err
}

const finalizeCompactionArtifact = `-- name: FinalizeCompactionArtifact :one
WITH requested_sources AS MATERIALIZED (
  SELECT
    requested_ids.message_id,
    requested_versions.source_version,
    requested_compacts.expected_compact_id,
    COALESCE(requested_ids.ordinal, requested_versions.ordinal, requested_compacts.ordinal)::bigint AS ordinal
  FROM unnest($1::uuid[])
    WITH ORDINALITY AS requested_ids(message_id, ordinal)
  FULL JOIN unnest($2::text[])
    WITH ORDINALITY AS requested_versions(source_version, ordinal)
    ON requested_versions.ordinal = requested_ids.ordinal
  FULL JOIN unnest($3::text[])
    WITH ORDINALITY AS requested_compacts(expected_compact_id, ordinal)
    ON requested_compacts.ordinal = COALESCE(requested_ids.ordinal, requested_versions.ordinal)
),
coverage_sources AS MATERIALIZED (
  SELECT
    covered.source->'ref'->>'id' AS source_id,
    covered.ordinal::bigint AS ordinal
  FROM jsonb_array_elements($4::jsonb)
    WITH ORDINALITY AS covered(source, ordinal)
),
request_shape AS MATERIALIZED (
  SELECT
    COUNT(*)::integer AS requested_count,
    COUNT(DISTINCT message_id)::integer AS unique_count,
    COALESCE(BOOL_AND(
      message_id IS NOT NULL
      AND COALESCE(BTRIM(source_version), '') <> ''
      AND expected_compact_id IS NOT NULL
      AND expected_compact_id <> ($5::uuid)::text
    ), false) AS valid
  FROM requested_sources
),
locked_compacts AS MATERIALIZED (
  SELECT compact.id, compact.bot_id, compact.session_id, compact.status
  FROM bot_history_message_compacts compact
  WHERE compact.id = $5
     OR EXISTS (
       SELECT 1
       FROM requested_sources requested
       WHERE requested.expected_compact_id = compact.id::text
     )
  ORDER BY compact.id
  FOR UPDATE OF compact
),
locked_log AS MATERIALIZED (
  SELECT compact.id
  FROM locked_compacts compact
  WHERE compact.id = $5
    AND compact.bot_id = $6
    AND compact.session_id = $7
    AND compact.status = 'pending'
),
eligible_request AS MATERIALIZED (
  SELECT shape.requested_count
  FROM request_shape shape
  WHERE shape.requested_count > 0
    AND shape.requested_count = shape.unique_count
    AND shape.valid
    AND cardinality($1::uuid[]) = cardinality($2::text[])
    AND cardinality($1::uuid[]) = cardinality($3::text[])
    AND COALESCE(
      (SELECT ARRAY_AGG(source_id ORDER BY ordinal) FROM coverage_sources),
      '{}'::text[]
    ) = COALESCE(
      (SELECT ARRAY_AGG(message_id::text ORDER BY ordinal) FROM requested_sources),
      '{}'::text[]
    )
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements($4::jsonb) AS covered(source)
      WHERE jsonb_typeof(covered.source) IS DISTINCT FROM 'object'
        OR jsonb_typeof(covered.source->'ref') IS DISTINCT FROM 'object'
        OR jsonb_typeof(covered.source->'ref'->'namespace') IS DISTINCT FROM 'string'
        OR COALESCE(BTRIM(covered.source->'ref'->>'namespace'), '') <> 'bot_history_message'
        OR jsonb_typeof(covered.source->'ref'->'id') IS DISTINCT FROM 'string'
        OR COALESCE(BTRIM(covered.source->'ref'->>'id'), '') = ''
        OR jsonb_typeof(covered.source->'ref'->'version') IS DISTINCT FROM 'number'
        OR COALESCE(covered.source->'ref'->>'version', '') <> '1'
        OR jsonb_typeof(covered.source->'ref'->'schema') IS DISTINCT FROM 'string'
        OR COALESCE(BTRIM(covered.source->'ref'->>'schema'), '') <> 'context_ref'
        OR jsonb_typeof(covered.source->'ref'->'durability') IS DISTINCT FROM 'string'
        OR COALESCE(BTRIM(covered.source->'ref'->>'durability'), '') <> 'durable'
        OR jsonb_typeof(covered.source->'ref'->'hash_algo') IS DISTINCT FROM 'string'
        OR COALESCE(BTRIM(covered.source->'ref'->>'hash_algo'), '') <> 'sha256'
        OR jsonb_typeof(covered.source->'ref'->'hash_scope') IS DISTINCT FROM 'string'
        OR COALESCE(BTRIM(covered.source->'ref'->>'hash_scope'), '') <> 'source_payload'
        OR jsonb_typeof(covered.source->'ref'->'content_hash') IS DISTINCT FROM 'string'
        OR COALESCE(covered.source->'ref'->>'content_hash', '') !~ '^[0-9a-f]{64}$'
        OR covered.source->'ref'->'range' IS NOT NULL
        OR jsonb_typeof(covered.source->'created_at_ms') IS DISTINCT FROM 'number'
        OR COALESCE(covered.source->>'created_at_ms', '') !~ '^[0-9]+$'
        OR (
          covered.source ? 'external_message_id'
          AND jsonb_typeof(covered.source->'external_message_id') IS DISTINCT FROM 'string'
        )
        OR (
          covered.source ? 'source_reply_to_message_id'
          AND jsonb_typeof(covered.source->'source_reply_to_message_id') IS DISTINCT FROM 'string'
        )
    )
    AND NOT EXISTS (
      SELECT 1
      FROM coverage_sources covered
      WHERE covered.ordinal > 1
        AND (
          $4::jsonb->((covered.ordinal - 1)::integer)->>'created_at_ms'
        )::bigint < (
          $4::jsonb->((covered.ordinal - 2)::integer)->>'created_at_ms'
        )::bigint
    )
    AND $8::bigint = (
      $4::jsonb->0->>'created_at_ms'
    )::bigint
    AND $9::bigint = (
      $4::jsonb->(jsonb_array_length($4::jsonb) - 1)->>'created_at_ms'
    )::bigint
),
locked_sources AS MATERIALIZED (
  SELECT message.id
  FROM bot_history_messages message
  JOIN requested_sources requested
    ON requested.message_id = message.id
   AND requested.source_version = message.xmin::text
   AND COALESCE(message.compact_id::text, '') = requested.expected_compact_id
  JOIN coverage_sources covered
    ON covered.ordinal = requested.ordinal
   AND covered.source_id = message.id::text
   AND (
     $4::jsonb->((requested.ordinal - 1)::integer)->>'created_at_ms'
   )::bigint = FLOOR(EXTRACT(EPOCH FROM message.created_at) * 1000)::bigint
  CROSS JOIN locked_log
  CROSS JOIN eligible_request
  WHERE message.bot_id = $6
    AND message.session_id = $7
    AND message.turn_visible = true
    AND message.turn_id IS NOT NULL
    AND message.turn_position IS NOT NULL
    AND message.turn_message_seq IS NOT NULL
    AND (message.metadata->>'trigger_mode' IS NULL OR message.metadata->>'trigger_mode' != 'passive_sync')
    AND (
      requested.expected_compact_id = ''
      OR EXISTS (
        SELECT 1
        FROM locked_compacts existing_compact
        WHERE existing_compact.id::text = requested.expected_compact_id
          AND existing_compact.bot_id = $6
          AND existing_compact.session_id = $7
          AND existing_compact.status <> 'ok'
      )
    )
  ORDER BY message.id
  FOR UPDATE OF message
),
claimed_sources AS (
  UPDATE bot_history_messages message
  SET compact_id = $5
  FROM locked_log, eligible_request request
  WHERE message.id IN (SELECT id FROM locked_sources)
    AND (SELECT COUNT(*) FROM locked_sources) = request.requested_count
  RETURNING message.id
),
finalization_stats AS MATERIALIZED (
  SELECT
    shape.requested_count,
    (SELECT COUNT(*) FROM locked_sources)::integer AS matched_count,
    (SELECT COUNT(*) FROM claimed_sources)::integer AS claimed_count
  FROM request_shape shape
),
finalized_state AS MATERIALIZED (
  SELECT (
    EXISTS (SELECT 1 FROM eligible_request)
    AND stats.matched_count = stats.requested_count
    AND stats.claimed_count = stats.requested_count
  ) AS finalized
  FROM finalization_stats stats
),
retired_pending_logs AS (
  UPDATE bot_history_message_compacts prior
  SET status = 'error',
      summary = '',
      message_count = 0,
      error_message = 'compaction source reclaimed by newer attempt',
      usage = NULL,
      model_id = NULL,
      coverage = '[]'::jsonb,
      anchor_start_ms = 0,
      anchor_end_ms = 0,
      completed_at = now()
  FROM locked_compacts locked, finalized_state state
  WHERE state.finalized
    AND prior.id = locked.id
    AND prior.id <> $5
    AND locked.status = 'pending'
  RETURNING prior.id
),
retirement_guard AS MATERIALIZED (
  SELECT COUNT(*)::integer AS retired_count FROM retired_pending_logs
),
completed_log AS (
  UPDATE bot_history_message_compacts compact
  SET status = CASE WHEN state.finalized THEN 'ok' ELSE 'error' END,
      summary = CASE WHEN state.finalized THEN $10 ELSE '' END,
      message_count = CASE WHEN state.finalized THEN shape.requested_count ELSE 0 END,
      error_message = CASE
        WHEN state.finalized THEN ''
        ELSE 'compaction source changed before finalization'
      END,
      usage = CASE WHEN state.finalized THEN $11::jsonb ELSE NULL::jsonb END,
      model_id = CASE WHEN state.finalized THEN $12::uuid ELSE NULL::uuid END,
      artifact_version = 1,
      coverage = CASE WHEN state.finalized THEN $4::jsonb ELSE '[]'::jsonb END,
      anchor_start_ms = CASE WHEN state.finalized THEN $8::bigint ELSE 0 END,
      anchor_end_ms = CASE WHEN state.finalized THEN $9::bigint ELSE 0 END,
      artifact_level = 0,
      parent_ids = '{}'::uuid[],
      completed_at = now()
  FROM locked_log, request_shape shape, finalized_state state, retirement_guard
  WHERE compact.id = locked_log.id
  RETURNING compact.status, state.finalized
)
SELECT
  COALESCE(completed.finalized, false)::boolean AS finalized,
  COALESCE(completed.status, '')::text AS status,
  stats.requested_count,
  stats.matched_count,
  stats.claimed_count
FROM finalization_stats stats
LEFT JOIN completed_log completed ON true
`

type FinalizeCompactionArtifactParams struct {
	MessageIds         []pgtype.UUID `json:"message_ids"`
	SourceVersions     []string      `json:"source_versions"`
	ExpectedCompactIds []string      `json:"expected_compact_ids"`
	Coverage           []byte        `json:"coverage"`
	CompactID          pgtype.UUID   `json:"compact_id"`
	BotID              pgtype.UUID   `json:"bot_id"`
	SessionID          pgtype.UUID   `json:"session_id"`
	AnchorStartMs      int64         `json:"anchor_start_ms"`
	AnchorEndMs        int64         `json:"anchor_end_ms"`
	Summary            string        `json:"summary"`
	Usage              []byte        `json:"usage"`
	ModelID            pgtype.UUID   `json:"model_id"`
}

type FinalizeCompactionArtifactRow struct {
	Finalized      bool   `json:"finalized"`
	Status         string `json:"status"`
	RequestedCount int32  `json:"requested_count"`
	MatchedCount   int32  `json:"matched_count"`
	ClaimedCount   int32  `json:"claimed_count"`
}

func (q *Queries) FinalizeCompactionArtifact(ctx context.Context, arg FinalizeCompactionArtifactParams) (FinalizeCompactionArtifactRow, error) {
	row := q.db.QueryRow(ctx, finalizeCompactionArtifact,
		arg.MessageIds,
		arg.SourceVersions,
		arg.ExpectedCompactIds,
		arg.Coverage,
		arg.CompactID,
		arg.BotID,
		arg.SessionID,
		arg.AnchorStartMs,
		arg.AnchorEndMs,
		arg.Summary,
		arg.Usage,
		arg.ModelID,
	)
	var i FinalizeCompactionArtifactRow
	err := row.Scan(
		&i.Finalized,
		&i.Status,
		&i.RequestedCount,
		&i.MatchedCount,
		&i.ClaimedCount,
	)
	return i, err
}

const getCompactionLogByID = `-- name: GetCompactionLogByID :one
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
       artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
       superseded_by, superseded_at, started_at, completed_at
FROM bot_history_message_compacts
WHERE id = $1
`

func (q *Queries) GetCompactionLogByID(ctx context.Context, id pgtype.UUID) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRow(ctx, getCompactionLogByID, id)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.ArtifactVersion,
		&i.Coverage,
		&i.AnchorStartMs,
		&i.AnchorEndMs,
		&i.ArtifactLevel,
		&i.ParentIds,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCompactionArtifactLineageBySession = `-- name: ListCompactionArtifactLineageBySession :many
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
       artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
       superseded_by, superseded_at, started_at, completed_at
FROM bot_history_message_compacts c
WHERE c.session_id = $1
  AND (
    c.status = 'ok'
    OR EXISTS (
      SELECT 1
      FROM bot_history_message_compacts parent
      WHERE parent.session_id = $1
        AND parent.status = 'ok'
        AND parent.superseded_by = c.id
    )
  )
ORDER BY c.anchor_start_ms ASC, c.started_at ASC, c.id ASC
`

func (q *Queries) ListCompactionArtifactLineageBySession(ctx context.Context, sessionID pgtype.UUID) ([]BotHistoryMessageCompact, error) {
	rows, err := q.db.Query(ctx, listCompactionArtifactLineageBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotHistoryMessageCompact
	for rows.Next() {
		var i BotHistoryMessageCompact
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.Summary,
			&i.MessageCount,
			&i.ErrorMessage,
			&i.Usage,
			&i.ModelID,
			&i.ArtifactVersion,
			&i.Coverage,
			&i.AnchorStartMs,
			&i.AnchorEndMs,
			&i.ArtifactLevel,
			&i.ParentIds,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompactionArtifactParentEdges = `-- name: ListCompactionArtifactParentEdges :many
SELECT parent_id, ordinal
FROM bot_history_message_compact_parent_edges
WHERE artifact_id = $1
ORDER BY ordinal ASC
`

type ListCompactionArtifactParentEdgesRow struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Ordinal  int32       `json:"ordinal"`
}

func (q *Queries) ListCompactionArtifactParentEdges(ctx context.Context, artifactID pgtype.UUID) ([]ListCompactionArtifactParentEdgesRow, error) {
	rows, err := q.db.Query(ctx, listCompactionArtifactParentEdges, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompactionArtifactParentEdgesRow
	for rows.Next() {
		var i ListCompactionArtifactParentEdgesRow
		if err := rows.Scan(&i.ParentID, &i.Ordinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompactionArtifactParentIDsBySuccessor = `-- name: ListCompactionArtifactParentIDsBySuccessor :many
SELECT id
FROM bot_history_message_compacts
WHERE superseded_by = $1
  AND bot_id = $2
  AND session_id IS NOT DISTINCT FROM $3::uuid
  AND status = 'ok'
ORDER BY id ASC
`

type ListCompactionArtifactParentIDsBySuccessorParams struct {
	SuccessorID pgtype.UUID `json:"successor_id"`
	BotID       pgtype.UUID `json:"bot_id"`
	SessionID   pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListCompactionArtifactParentIDsBySuccessor(ctx context.Context, arg ListCompactionArtifactParentIDsBySuccessorParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCompactionArtifactParentIDsBySuccessor, arg.SuccessorID, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompactionLogsByBot = `-- name: ListCompactionLogsByBot :many
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
       artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
       superseded_by, superseded_at, started_at, completed_at
FROM bot_history_message_compacts
WHERE bot_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListCompactionLogsByBotParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListCompactionLogsByBot(ctx context.Context, arg ListCompactionLogsByBotParams) ([]BotHistoryMessageCompact, error) {
	rows, err := q.db.Query(ctx, listCompactionLogsByBot, arg.BotID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotHistoryMessageCompact
	for rows.Next() {
		var i BotHistoryMessageCompact
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.Summary,
			&i.MessageCount,
			&i.ErrorMessage,
			&i.Usage,
			&i.ModelID,
			&i.ArtifactVersion,
			&i.Coverage,
			&i.AnchorStartMs,
			&i.AnchorEndMs,
			&i.ArtifactLevel,
			&i.ParentIds,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
