// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compaction_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeCompactionLog = `-- name: CompleteCompactionLog :one
UPDATE bot_history_message_compacts
SET status = $2,
    summary = $3,
    message_count = $4,
    error_message = $5,
    usage = $6,
    model_id = $7,
    coverage = $8,
    anchor_start_ms = $9,
    anchor_end_ms = $10,
    completed_at = now()
WHERE bot_history_message_compacts.id = $1
  AND status = 'pending'
  AND (
    $2 <> 'ok'
    OR session_id IS NULL
    OR EXISTS (
      SELECT 1
      FROM bot_sessions owner_session
      WHERE owner_session.id = bot_history_message_compacts.session_id
        AND owner_session.bot_id = bot_history_message_compacts.bot_id
        AND owner_session.compaction_epoch = bot_history_message_compacts.compaction_epoch
    )
  )
RETURNING id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
          artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
          superseded_by, superseded_at, compaction_epoch, started_at, completed_at
`

type CompleteCompactionLogParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	Summary       string      `json:"summary"`
	MessageCount  int32       `json:"message_count"`
	ErrorMessage  string      `json:"error_message"`
	Usage         []byte      `json:"usage"`
	ModelID       pgtype.UUID `json:"model_id"`
	Coverage      []byte      `json:"coverage"`
	AnchorStartMs int64       `json:"anchor_start_ms"`
	AnchorEndMs   int64       `json:"anchor_end_ms"`
}

func (q *Queries) CompleteCompactionLog(ctx context.Context, arg CompleteCompactionLogParams) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRow(ctx, completeCompactionLog,
		arg.ID,
		arg.Status,
		arg.Summary,
		arg.MessageCount,
		arg.ErrorMessage,
		arg.Usage,
		arg.ModelID,
		arg.Coverage,
		arg.AnchorStartMs,
		arg.AnchorEndMs,
	)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.ArtifactVersion,
		&i.Coverage,
		&i.AnchorStartMs,
		&i.AnchorEndMs,
		&i.ArtifactLevel,
		&i.ParentIds,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CompactionEpoch,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCompactionLogsByBot = `-- name: CountCompactionLogsByBot :one
SELECT count(*) FROM bot_history_message_compacts WHERE bot_id = $1
`

func (q *Queries) CountCompactionLogsByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompactionLogsByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompactionLog = `-- name: CreateCompactionLog :one
INSERT INTO bot_history_message_compacts (bot_id, session_id, compaction_epoch)
SELECT $1, owner_session.id, owner_session.compaction_epoch
FROM bot_sessions owner_session
WHERE owner_session.id = $2
  AND owner_session.bot_id = $1
  AND owner_session.compaction_epoch = $3
RETURNING id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
          artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
          superseded_by, superseded_at, compaction_epoch, started_at, completed_at
`

type CreateCompactionLogParams struct {
	BotID         pgtype.UUID `json:"bot_id"`
	SessionID     pgtype.UUID `json:"session_id"`
	ExpectedEpoch int64       `json:"expected_epoch"`
}

func (q *Queries) CreateCompactionLog(ctx context.Context, arg CreateCompactionLogParams) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRow(ctx, createCompactionLog, arg.BotID, arg.SessionID, arg.ExpectedEpoch)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.ArtifactVersion,
		&i.Coverage,
		&i.AnchorStartMs,
		&i.AnchorEndMs,
		&i.ArtifactLevel,
		&i.ParentIds,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CompactionEpoch,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteCompactionLogsByBot = `-- name: DeleteCompactionLogsByBot :exec
WITH invalidated_sessions AS (
  UPDATE bot_sessions
  SET compaction_epoch = compaction_epoch + 1
  WHERE bot_id = $1
  RETURNING id
)
DELETE FROM bot_history_message_compacts AS compacts
WHERE compacts.bot_id = $1
  AND (SELECT count(*) FROM invalidated_sessions) >= 0
`

func (q *Queries) DeleteCompactionLogsByBot(ctx context.Context, targetBotID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompactionLogsByBot, targetBotID)
	return err
}

const getCompactionLogByID = `-- name: GetCompactionLogByID :one
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
       artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
       superseded_by, superseded_at, compaction_epoch, started_at, completed_at
FROM bot_history_message_compacts compact
WHERE compact.id = $1
  AND (
    compact.session_id IS NULL
    OR EXISTS (
      SELECT 1
      FROM bot_sessions owner_session
      WHERE owner_session.id = compact.session_id
        AND owner_session.bot_id = compact.bot_id
        AND owner_session.compaction_epoch = compact.compaction_epoch
    )
  )
`

func (q *Queries) GetCompactionLogByID(ctx context.Context, id pgtype.UUID) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRow(ctx, getCompactionLogByID, id)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.ArtifactVersion,
		&i.Coverage,
		&i.AnchorStartMs,
		&i.AnchorEndMs,
		&i.ArtifactLevel,
		&i.ParentIds,
		&i.SupersededBy,
		&i.SupersededAt,
		&i.CompactionEpoch,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCompactionArtifactLineageBySession = `-- name: ListCompactionArtifactLineageBySession :many
SELECT c.id, c.bot_id, c.session_id, c.status, c.summary, c.message_count, c.error_message, c.usage, c.model_id,
       c.artifact_version, c.coverage, c.anchor_start_ms, c.anchor_end_ms, c.artifact_level, c.parent_ids,
       c.superseded_by, c.superseded_at, c.compaction_epoch, c.started_at, c.completed_at
FROM bot_history_message_compacts c
JOIN bot_sessions owner_session
  ON owner_session.id = $1
 AND owner_session.bot_id = c.bot_id
WHERE c.session_id = owner_session.id
  AND c.compaction_epoch = owner_session.compaction_epoch
  AND (
    c.status = 'ok'
    OR EXISTS (
      SELECT 1
      FROM bot_history_message_compacts parent
      WHERE parent.bot_id = owner_session.bot_id
        AND parent.session_id = owner_session.id
        AND parent.compaction_epoch = owner_session.compaction_epoch
        AND parent.status = 'ok'
        AND parent.superseded_by = c.id
    )
  )
ORDER BY c.anchor_start_ms ASC, c.started_at ASC, c.id ASC
`

func (q *Queries) ListCompactionArtifactLineageBySession(ctx context.Context, id pgtype.UUID) ([]BotHistoryMessageCompact, error) {
	rows, err := q.db.Query(ctx, listCompactionArtifactLineageBySession, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotHistoryMessageCompact
	for rows.Next() {
		var i BotHistoryMessageCompact
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.Summary,
			&i.MessageCount,
			&i.ErrorMessage,
			&i.Usage,
			&i.ModelID,
			&i.ArtifactVersion,
			&i.Coverage,
			&i.AnchorStartMs,
			&i.AnchorEndMs,
			&i.ArtifactLevel,
			&i.ParentIds,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.CompactionEpoch,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompactionArtifactParentIDsBySuccessor = `-- name: ListCompactionArtifactParentIDsBySuccessor :many
SELECT parent.id
FROM bot_history_message_compacts parent
JOIN bot_sessions owner_session
  ON owner_session.id = $1::uuid
 AND owner_session.bot_id = $2
WHERE parent.superseded_by = $3
  AND parent.bot_id = owner_session.bot_id
  AND parent.session_id = owner_session.id
  AND parent.compaction_epoch = owner_session.compaction_epoch
  AND parent.status = 'ok'
  AND EXISTS (
    SELECT 1
    FROM bot_history_message_compacts successor
    WHERE successor.id = parent.superseded_by
      AND successor.bot_id = owner_session.bot_id
      AND successor.session_id = owner_session.id
      AND successor.compaction_epoch = owner_session.compaction_epoch
  )
ORDER BY parent.id ASC
`

type ListCompactionArtifactParentIDsBySuccessorParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	BotID       pgtype.UUID `json:"bot_id"`
	SuccessorID pgtype.UUID `json:"successor_id"`
}

func (q *Queries) ListCompactionArtifactParentIDsBySuccessor(ctx context.Context, arg ListCompactionArtifactParentIDsBySuccessorParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCompactionArtifactParentIDsBySuccessor, arg.SessionID, arg.BotID, arg.SuccessorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompactionLogsByBot = `-- name: ListCompactionLogsByBot :many
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id,
       artifact_version, coverage, anchor_start_ms, anchor_end_ms, artifact_level, parent_ids,
       superseded_by, superseded_at, compaction_epoch, started_at, completed_at
FROM bot_history_message_compacts
WHERE bot_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListCompactionLogsByBotParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListCompactionLogsByBot(ctx context.Context, arg ListCompactionLogsByBotParams) ([]BotHistoryMessageCompact, error) {
	rows, err := q.db.Query(ctx, listCompactionLogsByBot, arg.BotID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotHistoryMessageCompact
	for rows.Next() {
		var i BotHistoryMessageCompact
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.Summary,
			&i.MessageCount,
			&i.ErrorMessage,
			&i.Usage,
			&i.ModelID,
			&i.ArtifactVersion,
			&i.Coverage,
			&i.AnchorStartMs,
			&i.AnchorEndMs,
			&i.ArtifactLevel,
			&i.ParentIds,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.CompactionEpoch,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
