// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailProvider = `-- name: CreateEmailProvider :one
INSERT INTO email_providers (team_id, user_id, name, provider, config)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, user_id, name, provider, config, created_at, updated_at, team_id
`

type CreateEmailProviderParams struct {
	TeamID   pgtype.UUID `json:"team_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Provider string      `json:"provider"`
	Config   []byte      `json:"config"`
}

func (q *Queries) CreateEmailProvider(ctx context.Context, arg CreateEmailProviderParams) (EmailProvider, error) {
	row := q.db.QueryRow(ctx, createEmailProvider,
		arg.TeamID,
		arg.UserID,
		arg.Name,
		arg.Provider,
		arg.Config,
	)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const deleteEmailProvider = `-- name: DeleteEmailProvider :exec
DELETE FROM email_providers
WHERE id = $1
  AND team_id = $2
`

type DeleteEmailProviderParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteEmailProvider(ctx context.Context, arg DeleteEmailProviderParams) error {
	_, err := q.db.Exec(ctx, deleteEmailProvider, arg.ID, arg.TeamID)
	return err
}

const deleteEmailProviderByIDAndUser = `-- name: DeleteEmailProviderByIDAndUser :exec
DELETE FROM email_providers
WHERE id = $1
  AND team_id = $2
  AND user_id = $3
`

type DeleteEmailProviderByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteEmailProviderByIDAndUser(ctx context.Context, arg DeleteEmailProviderByIDAndUserParams) error {
	_, err := q.db.Exec(ctx, deleteEmailProviderByIDAndUser, arg.ID, arg.TeamID, arg.UserID)
	return err
}

const getEmailProviderByID = `-- name: GetEmailProviderByID :one
SELECT id, user_id, name, provider, config, created_at, updated_at, team_id FROM email_providers
WHERE id = $1
  AND team_id = $2
`

type GetEmailProviderByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) GetEmailProviderByID(ctx context.Context, arg GetEmailProviderByIDParams) (EmailProvider, error) {
	row := q.db.QueryRow(ctx, getEmailProviderByID, arg.ID, arg.TeamID)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getEmailProviderByIDAndUser = `-- name: GetEmailProviderByIDAndUser :one
SELECT id, user_id, name, provider, config, created_at, updated_at, team_id FROM email_providers
WHERE id = $1
  AND team_id = $2
  AND user_id = $3
`

type GetEmailProviderByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetEmailProviderByIDAndUser(ctx context.Context, arg GetEmailProviderByIDAndUserParams) (EmailProvider, error) {
	row := q.db.QueryRow(ctx, getEmailProviderByIDAndUser, arg.ID, arg.TeamID, arg.UserID)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getEmailProviderByNameAndUser = `-- name: GetEmailProviderByNameAndUser :one
SELECT id, user_id, name, provider, config, created_at, updated_at, team_id FROM email_providers
WHERE team_id = $1
  AND user_id = $2
  AND name = $3
`

type GetEmailProviderByNameAndUserParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) GetEmailProviderByNameAndUser(ctx context.Context, arg GetEmailProviderByNameAndUserParams) (EmailProvider, error) {
	row := q.db.QueryRow(ctx, getEmailProviderByNameAndUser, arg.TeamID, arg.UserID, arg.Name)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const listEmailProviders = `-- name: ListEmailProviders :many
SELECT id, user_id, name, provider, config, created_at, updated_at, team_id FROM email_providers
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEmailProviders(ctx context.Context, teamID pgtype.UUID) ([]EmailProvider, error) {
	rows, err := q.db.Query(ctx, listEmailProviders, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailProvider
	for rows.Next() {
		var i EmailProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailProvidersByProvider = `-- name: ListEmailProvidersByProvider :many
SELECT id, user_id, name, provider, config, created_at, updated_at, team_id FROM email_providers
WHERE team_id = $1
  AND provider = $2
ORDER BY created_at DESC
`

type ListEmailProvidersByProviderParams struct {
	TeamID   pgtype.UUID `json:"team_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) ListEmailProvidersByProvider(ctx context.Context, arg ListEmailProvidersByProviderParams) ([]EmailProvider, error) {
	rows, err := q.db.Query(ctx, listEmailProvidersByProvider, arg.TeamID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailProvider
	for rows.Next() {
		var i EmailProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailProvidersByUser = `-- name: ListEmailProvidersByUser :many
SELECT id, user_id, name, provider, config, created_at, updated_at, team_id FROM email_providers
WHERE team_id = $1
  AND user_id = $2
ORDER BY created_at DESC
`

type ListEmailProvidersByUserParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListEmailProvidersByUser(ctx context.Context, arg ListEmailProvidersByUserParams) ([]EmailProvider, error) {
	rows, err := q.db.Query(ctx, listEmailProvidersByUser, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailProvider
	for rows.Next() {
		var i EmailProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailProvidersByUserAndProvider = `-- name: ListEmailProvidersByUserAndProvider :many
SELECT id, user_id, name, provider, config, created_at, updated_at, team_id FROM email_providers
WHERE team_id = $1
  AND user_id = $2
  AND provider = $3
ORDER BY created_at DESC
`

type ListEmailProvidersByUserAndProviderParams struct {
	TeamID   pgtype.UUID `json:"team_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) ListEmailProvidersByUserAndProvider(ctx context.Context, arg ListEmailProvidersByUserAndProviderParams) ([]EmailProvider, error) {
	rows, err := q.db.Query(ctx, listEmailProvidersByUserAndProvider, arg.TeamID, arg.UserID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailProvider
	for rows.Next() {
		var i EmailProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailProvider = `-- name: UpdateEmailProvider :one
UPDATE email_providers
SET
  name = $1,
  provider = $2,
  config = $3,
  updated_at = now()
WHERE id = $4
  AND team_id = $5
RETURNING id, user_id, name, provider, config, created_at, updated_at, team_id
`

type UpdateEmailProviderParams struct {
	Name     string      `json:"name"`
	Provider string      `json:"provider"`
	Config   []byte      `json:"config"`
	ID       pgtype.UUID `json:"id"`
	TeamID   pgtype.UUID `json:"team_id"`
}

func (q *Queries) UpdateEmailProvider(ctx context.Context, arg UpdateEmailProviderParams) (EmailProvider, error) {
	row := q.db.QueryRow(ctx, updateEmailProvider,
		arg.Name,
		arg.Provider,
		arg.Config,
		arg.ID,
		arg.TeamID,
	)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const updateEmailProviderByIDAndUser = `-- name: UpdateEmailProviderByIDAndUser :one
UPDATE email_providers
SET
  name = $1,
  provider = $2,
  config = $3,
  updated_at = now()
WHERE id = $4
  AND team_id = $5
  AND user_id = $6
RETURNING id, user_id, name, provider, config, created_at, updated_at, team_id
`

type UpdateEmailProviderByIDAndUserParams struct {
	Name     string      `json:"name"`
	Provider string      `json:"provider"`
	Config   []byte      `json:"config"`
	ID       pgtype.UUID `json:"id"`
	TeamID   pgtype.UUID `json:"team_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateEmailProviderByIDAndUser(ctx context.Context, arg UpdateEmailProviderByIDAndUserParams) (EmailProvider, error) {
	row := q.db.QueryRow(ctx, updateEmailProviderByIDAndUser,
		arg.Name,
		arg.Provider,
		arg.Config,
		arg.ID,
		arg.TeamID,
		arg.UserID,
	)
	var i EmailProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
