// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_bindings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBotEmailBinding = `-- name: CreateBotEmailBinding :one
INSERT INTO bot_email_bindings (bot_id, email_provider_id, email_address, can_read, can_write, can_delete, config)
SELECT
  b.id,
  ep.id,
  $1,
  $2,
  $3,
  $4,
  $5
FROM bots b
JOIN email_providers ep ON ep.id = $6
WHERE b.id = $7
  AND b.team_id = $8
  AND ep.team_id = $8
RETURNING id, bot_id, email_provider_id, email_address, can_read, can_write, can_delete, config, created_at, updated_at, team_id
`

type CreateBotEmailBindingParams struct {
	EmailAddress    string      `json:"email_address"`
	CanRead         bool        `json:"can_read"`
	CanWrite        bool        `json:"can_write"`
	CanDelete       bool        `json:"can_delete"`
	Config          []byte      `json:"config"`
	EmailProviderID pgtype.UUID `json:"email_provider_id"`
	BotID           pgtype.UUID `json:"bot_id"`
	TeamID          pgtype.UUID `json:"team_id"`
}

func (q *Queries) CreateBotEmailBinding(ctx context.Context, arg CreateBotEmailBindingParams) (BotEmailBinding, error) {
	row := q.db.QueryRow(ctx, createBotEmailBinding,
		arg.EmailAddress,
		arg.CanRead,
		arg.CanWrite,
		arg.CanDelete,
		arg.Config,
		arg.EmailProviderID,
		arg.BotID,
		arg.TeamID,
	)
	var i BotEmailBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.EmailProviderID,
		&i.EmailAddress,
		&i.CanRead,
		&i.CanWrite,
		&i.CanDelete,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const deleteBotEmailBinding = `-- name: DeleteBotEmailBinding :exec
DELETE FROM bot_email_bindings AS beb
USING bots b, email_providers ep
WHERE beb.id = $1
  AND b.id = beb.bot_id
  AND ep.id = beb.email_provider_id
  AND b.team_id = $2
  AND ep.team_id = $2
`

type DeleteBotEmailBindingParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteBotEmailBinding(ctx context.Context, arg DeleteBotEmailBindingParams) error {
	_, err := q.db.Exec(ctx, deleteBotEmailBinding, arg.ID, arg.TeamID)
	return err
}

const getBotEmailBindingByBotAndProvider = `-- name: GetBotEmailBindingByBotAndProvider :one
SELECT beb.id, beb.bot_id, beb.email_provider_id, beb.email_address, beb.can_read, beb.can_write, beb.can_delete, beb.config, beb.created_at, beb.updated_at, beb.team_id
FROM bot_email_bindings beb
JOIN bots b ON b.id = beb.bot_id
JOIN email_providers ep ON ep.id = beb.email_provider_id
WHERE beb.bot_id = $1
  AND beb.email_provider_id = $2
  AND b.team_id = $3
  AND ep.team_id = $3
`

type GetBotEmailBindingByBotAndProviderParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	EmailProviderID pgtype.UUID `json:"email_provider_id"`
	TeamID          pgtype.UUID `json:"team_id"`
}

func (q *Queries) GetBotEmailBindingByBotAndProvider(ctx context.Context, arg GetBotEmailBindingByBotAndProviderParams) (BotEmailBinding, error) {
	row := q.db.QueryRow(ctx, getBotEmailBindingByBotAndProvider, arg.BotID, arg.EmailProviderID, arg.TeamID)
	var i BotEmailBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.EmailProviderID,
		&i.EmailAddress,
		&i.CanRead,
		&i.CanWrite,
		&i.CanDelete,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getBotEmailBindingByID = `-- name: GetBotEmailBindingByID :one
SELECT beb.id, beb.bot_id, beb.email_provider_id, beb.email_address, beb.can_read, beb.can_write, beb.can_delete, beb.config, beb.created_at, beb.updated_at, beb.team_id
FROM bot_email_bindings beb
JOIN bots b ON b.id = beb.bot_id
JOIN email_providers ep ON ep.id = beb.email_provider_id
WHERE beb.id = $1
  AND b.team_id = $2
  AND ep.team_id = $2
`

type GetBotEmailBindingByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) GetBotEmailBindingByID(ctx context.Context, arg GetBotEmailBindingByIDParams) (BotEmailBinding, error) {
	row := q.db.QueryRow(ctx, getBotEmailBindingByID, arg.ID, arg.TeamID)
	var i BotEmailBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.EmailProviderID,
		&i.EmailAddress,
		&i.CanRead,
		&i.CanWrite,
		&i.CanDelete,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const listBotEmailBindings = `-- name: ListBotEmailBindings :many
SELECT beb.id, beb.bot_id, beb.email_provider_id, beb.email_address, beb.can_read, beb.can_write, beb.can_delete, beb.config, beb.created_at, beb.updated_at, beb.team_id
FROM bot_email_bindings beb
JOIN bots b ON b.id = beb.bot_id
JOIN email_providers ep ON ep.id = beb.email_provider_id
WHERE beb.bot_id = $1
  AND b.team_id = $2
  AND ep.team_id = $2
ORDER BY beb.created_at DESC
`

type ListBotEmailBindingsParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) ListBotEmailBindings(ctx context.Context, arg ListBotEmailBindingsParams) ([]BotEmailBinding, error) {
	rows, err := q.db.Query(ctx, listBotEmailBindings, arg.BotID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotEmailBinding
	for rows.Next() {
		var i BotEmailBinding
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.EmailProviderID,
			&i.EmailAddress,
			&i.CanRead,
			&i.CanWrite,
			&i.CanDelete,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotEmailBindingsByProvider = `-- name: ListBotEmailBindingsByProvider :many
SELECT beb.id, beb.bot_id, beb.email_provider_id, beb.email_address, beb.can_read, beb.can_write, beb.can_delete, beb.config, beb.created_at, beb.updated_at, beb.team_id
FROM bot_email_bindings beb
JOIN bots b ON b.id = beb.bot_id
JOIN email_providers ep ON ep.id = beb.email_provider_id
WHERE beb.email_provider_id = $1
  AND b.team_id = $2
  AND ep.team_id = $2
ORDER BY beb.created_at DESC
`

type ListBotEmailBindingsByProviderParams struct {
	EmailProviderID pgtype.UUID `json:"email_provider_id"`
	TeamID          pgtype.UUID `json:"team_id"`
}

func (q *Queries) ListBotEmailBindingsByProvider(ctx context.Context, arg ListBotEmailBindingsByProviderParams) ([]BotEmailBinding, error) {
	rows, err := q.db.Query(ctx, listBotEmailBindingsByProvider, arg.EmailProviderID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotEmailBinding
	for rows.Next() {
		var i BotEmailBinding
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.EmailProviderID,
			&i.EmailAddress,
			&i.CanRead,
			&i.CanWrite,
			&i.CanDelete,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadableBindingsByProvider = `-- name: ListReadableBindingsByProvider :many
SELECT beb.id, beb.bot_id, beb.email_provider_id, beb.email_address, beb.can_read, beb.can_write, beb.can_delete, beb.config, beb.created_at, beb.updated_at, beb.team_id
FROM bot_email_bindings beb
JOIN bots b ON b.id = beb.bot_id
JOIN email_providers ep ON ep.id = beb.email_provider_id
WHERE beb.email_provider_id = $1
  AND beb.can_read = TRUE
  AND b.team_id = $2
  AND ep.team_id = $2
ORDER BY beb.created_at DESC
`

type ListReadableBindingsByProviderParams struct {
	EmailProviderID pgtype.UUID `json:"email_provider_id"`
	TeamID          pgtype.UUID `json:"team_id"`
}

func (q *Queries) ListReadableBindingsByProvider(ctx context.Context, arg ListReadableBindingsByProviderParams) ([]BotEmailBinding, error) {
	rows, err := q.db.Query(ctx, listReadableBindingsByProvider, arg.EmailProviderID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotEmailBinding
	for rows.Next() {
		var i BotEmailBinding
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.EmailProviderID,
			&i.EmailAddress,
			&i.CanRead,
			&i.CanWrite,
			&i.CanDelete,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotEmailBinding = `-- name: UpdateBotEmailBinding :one
UPDATE bot_email_bindings AS beb
SET
  email_address = $1,
  can_read = $2,
  can_write = $3,
  can_delete = $4,
  config = $5,
  updated_at = now()
FROM bots b, email_providers ep
WHERE beb.id = $6
  AND b.id = beb.bot_id
  AND ep.id = beb.email_provider_id
  AND b.team_id = $7
  AND ep.team_id = $7
RETURNING beb.id, beb.bot_id, beb.email_provider_id, beb.email_address, beb.can_read, beb.can_write, beb.can_delete, beb.config, beb.created_at, beb.updated_at, beb.team_id
`

type UpdateBotEmailBindingParams struct {
	EmailAddress string      `json:"email_address"`
	CanRead      bool        `json:"can_read"`
	CanWrite     bool        `json:"can_write"`
	CanDelete    bool        `json:"can_delete"`
	Config       []byte      `json:"config"`
	ID           pgtype.UUID `json:"id"`
	TeamID       pgtype.UUID `json:"team_id"`
}

func (q *Queries) UpdateBotEmailBinding(ctx context.Context, arg UpdateBotEmailBindingParams) (BotEmailBinding, error) {
	row := q.db.QueryRow(ctx, updateBotEmailBinding,
		arg.EmailAddress,
		arg.CanRead,
		arg.CanWrite,
		arg.CanDelete,
		arg.Config,
		arg.ID,
		arg.TeamID,
	)
	var i BotEmailBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.EmailProviderID,
		&i.EmailAddress,
		&i.CanRead,
		&i.CanWrite,
		&i.CanDelete,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
