// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessagesByBot = `-- name: CountMessagesByBot :one
SELECT COUNT(*) FROM bot_history_messages
WHERE bot_id = $1
`

func (q *Queries) CountMessagesByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO bot_history_messages (
  bot_id,
  session_id,
  branch_id,
  branch_seq,
  sender_channel_identity_id,
  sender_account_user_id,
  source_message_id,
  source_reply_to_message_id,
  role,
  content,
  metadata,
  usage,
  model_id,
  event_id,
  display_text
)
VALUES (
  $1,
  $2::uuid,
  $3::uuid,
  CASE
    WHEN $3::uuid IS NULL THEN NULL
    ELSE (
      SELECT COALESCE(MAX(existing.branch_seq), 0) + 1
      FROM bot_history_messages existing
      WHERE existing.branch_id = $3::uuid
    )
  END,
  $4::uuid,
  $5::uuid,
  $6::text,
  $7::text,
  $8,
  $9,
  $10,
  $11,
  $12::uuid,
  $13::uuid,
  $14::text
)
RETURNING
  id,
  bot_id,
  session_id,
  branch_id,
  branch_seq,
  sender_channel_identity_id,
  sender_account_user_id AS sender_user_id,
  source_message_id AS external_message_id,
  source_reply_to_message_id,
  role,
  content,
  metadata,
  usage,
  event_id,
  display_text,
  created_at
`

type CreateMessageParams struct {
	BotID                   pgtype.UUID `json:"bot_id"`
	SessionID               pgtype.UUID `json:"session_id"`
	BranchID                pgtype.UUID `json:"branch_id"`
	SenderChannelIdentityID pgtype.UUID `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text `json:"source_reply_to_message_id"`
	Role                    string      `json:"role"`
	Content                 []byte      `json:"content"`
	Metadata                []byte      `json:"metadata"`
	Usage                   []byte      `json:"usage"`
	ModelID                 pgtype.UUID `json:"model_id"`
	EventID                 pgtype.UUID `json:"event_id"`
	DisplayText             pgtype.Text `json:"display_text"`
}

type CreateMessageRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.BotID,
		arg.SessionID,
		arg.BranchID,
		arg.SenderChannelIdentityID,
		arg.SenderUserID,
		arg.ExternalMessageID,
		arg.SourceReplyToMessageID,
		arg.Role,
		arg.Content,
		arg.Metadata,
		arg.Usage,
		arg.ModelID,
		arg.EventID,
		arg.DisplayText,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.BranchID,
		&i.BranchSeq,
		&i.SenderChannelIdentityID,
		&i.SenderUserID,
		&i.ExternalMessageID,
		&i.SourceReplyToMessageID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.Usage,
		&i.EventID,
		&i.DisplayText,
		&i.CreatedAt,
	)
	return i, err
}

const createRootSessionBranch = `-- name: CreateRootSessionBranch :one
INSERT INTO bot_session_branches (session_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateRootSessionBranch(ctx context.Context, sessionID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRootSessionBranch, sessionID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSessionBranchFromMessage = `-- name: CreateSessionBranchFromMessage :one
INSERT INTO bot_session_branches (
  session_id,
  parent_branch_id,
  fork_from_message_id,
  fork_from_seq,
  title
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id
`

type CreateSessionBranchFromMessageParams struct {
	SessionID         pgtype.UUID `json:"session_id"`
	ParentBranchID    pgtype.UUID `json:"parent_branch_id"`
	ForkFromMessageID pgtype.UUID `json:"fork_from_message_id"`
	ForkFromSeq       pgtype.Int8 `json:"fork_from_seq"`
	Title             pgtype.Text `json:"title"`
}

func (q *Queries) CreateSessionBranchFromMessage(ctx context.Context, arg CreateSessionBranchFromMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSessionBranchFromMessage,
		arg.SessionID,
		arg.ParentBranchID,
		arg.ForkFromMessageID,
		arg.ForkFromSeq,
		arg.Title,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteMessagesByBot = `-- name: DeleteMessagesByBot :exec
DELETE FROM bot_history_messages
WHERE bot_id = $1
`

func (q *Queries) DeleteMessagesByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesByBot, botID)
	return err
}

const deleteMessagesBySession = `-- name: DeleteMessagesBySession :exec
DELETE FROM bot_history_messages
WHERE session_id = $1
`

func (q *Queries) DeleteMessagesBySession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesBySession, sessionID)
	return err
}

const getActiveSessionBranch = `-- name: GetActiveSessionBranch :one
SELECT active_branch_id
FROM bot_sessions
WHERE id = $1
`

func (q *Queries) GetActiveSessionBranch(ctx context.Context, sessionID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveSessionBranch, sessionID)
	var active_branch_id pgtype.UUID
	err := row.Scan(&active_branch_id)
	return active_branch_id, err
}

const getMessageByExternalIDBySession = `-- name: GetMessageByExternalIDBySession :one
WITH RECURSIVE branch_path AS (
  SELECT b.id AS branch_id, b.parent_branch_id, NULL::BIGINT AS max_seq, 0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(s.active_branch_id, (
    SELECT rb.id FROM bot_session_branches rb
    WHERE rb.session_id = s.id AND rb.parent_branch_id IS NULL AND rb.fork_from_message_id IS NULL
    ORDER BY rb.created_at ASC LIMIT 1
  ))
  WHERE s.id = $1
  UNION ALL
  SELECT parent.id, parent.parent_branch_id, child.fork_from_seq, bp.depth + 1
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND m.source_message_id = $2
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
ORDER BY COALESCE(bp.depth, -1) ASC, COALESCE(m.branch_seq, 0) DESC, m.created_at DESC
LIMIT 1
`

type GetMessageByExternalIDBySessionParams struct {
	SessionID         pgtype.UUID `json:"session_id"`
	ExternalMessageID pgtype.Text `json:"external_message_id"`
}

type GetMessageByExternalIDBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) GetMessageByExternalIDBySession(ctx context.Context, arg GetMessageByExternalIDBySessionParams) (GetMessageByExternalIDBySessionRow, error) {
	row := q.db.QueryRow(ctx, getMessageByExternalIDBySession, arg.SessionID, arg.ExternalMessageID)
	var i GetMessageByExternalIDBySessionRow
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.BranchID,
		&i.BranchSeq,
		&i.SenderChannelIdentityID,
		&i.SenderUserID,
		&i.ExternalMessageID,
		&i.SourceReplyToMessageID,
		&i.Role,
		&i.Content,
		&i.Metadata,
		&i.Usage,
		&i.EventID,
		&i.DisplayText,
		&i.CreatedAt,
		&i.SenderDisplayName,
		&i.SenderAvatarUrl,
		&i.Platform,
	)
	return i, err
}

const getMessageForSessionBranchFork = `-- name: GetMessageForSessionBranchFork :one
SELECT
  m.id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.role,
  m.created_at
FROM bot_history_messages m
WHERE m.id = $1
  AND m.session_id = $2
LIMIT 1
`

type GetMessageForSessionBranchForkParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type GetMessageForSessionBranchForkRow struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	BranchID  pgtype.UUID        `json:"branch_id"`
	BranchSeq pgtype.Int8        `json:"branch_seq"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMessageForSessionBranchFork(ctx context.Context, arg GetMessageForSessionBranchForkParams) (GetMessageForSessionBranchForkRow, error) {
	row := q.db.QueryRow(ctx, getMessageForSessionBranchFork, arg.MessageID, arg.SessionID)
	var i GetMessageForSessionBranchForkRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.BranchSeq,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getRootSessionBranch = `-- name: GetRootSessionBranch :one
SELECT id
FROM bot_session_branches
WHERE session_id = $1
  AND parent_branch_id IS NULL
  AND fork_from_message_id IS NULL
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetRootSessionBranch(ctx context.Context, sessionID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRootSessionBranch, sessionID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getSessionBranchForkPoint = `-- name: GetSessionBranchForkPoint :one
WITH turn_start AS (
  SELECT COALESCE((
    SELECT MAX(u.branch_seq)
    FROM bot_history_messages u
    WHERE u.session_id = $1::uuid
      AND u.branch_id = $2::uuid
      AND u.role = 'user'
      AND u.branch_seq < $3::bigint
  ), $3::bigint) AS branch_seq
)
SELECT COALESCE((
  SELECT MAX(prev.branch_seq)
  FROM bot_history_messages prev, turn_start ts
  WHERE prev.session_id = $1::uuid
    AND prev.branch_id = $2::uuid
    AND prev.role = 'assistant'
    AND prev.branch_seq < ts.branch_seq
), 0)::bigint AS fork_from_seq
`

type GetSessionBranchForkPointParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BranchID  pgtype.UUID `json:"branch_id"`
	BranchSeq int64       `json:"branch_seq"`
}

func (q *Queries) GetSessionBranchForkPoint(ctx context.Context, arg GetSessionBranchForkPointParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionBranchForkPoint, arg.SessionID, arg.BranchID, arg.BranchSeq)
	var fork_from_seq int64
	err := row.Scan(&fork_from_seq)
	return fork_from_seq, err
}

const listActiveMessagesSince = `-- name: ListActiveMessagesSince :many
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.compact_id,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
WHERE m.bot_id = $1
  AND m.created_at >= $2
  AND (m.metadata->>'trigger_mode' IS NULL OR m.metadata->>'trigger_mode' != 'passive_sync')
ORDER BY m.created_at ASC
`

type ListActiveMessagesSinceParams struct {
	BotID     pgtype.UUID        `json:"bot_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ListActiveMessagesSinceRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CompactID               pgtype.UUID        `json:"compact_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListActiveMessagesSince(ctx context.Context, arg ListActiveMessagesSinceParams) ([]ListActiveMessagesSinceRow, error) {
	rows, err := q.db.Query(ctx, listActiveMessagesSince, arg.BotID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMessagesSinceRow
	for rows.Next() {
		var i ListActiveMessagesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CompactID,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMessagesSinceBySession = `-- name: ListActiveMessagesSinceBySession :many
WITH RECURSIVE branch_path AS (
  SELECT b.id AS branch_id, b.parent_branch_id, NULL::BIGINT AS max_seq, 0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(s.active_branch_id, (
    SELECT rb.id FROM bot_session_branches rb
    WHERE rb.session_id = s.id AND rb.parent_branch_id IS NULL AND rb.fork_from_message_id IS NULL
    ORDER BY rb.created_at ASC LIMIT 1
  ))
  WHERE s.id = $1
  UNION ALL
  SELECT parent.id, parent.parent_branch_id, child.fork_from_seq, bp.depth + 1
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.compact_id,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND m.created_at >= $2
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
  AND (m.metadata->>'trigger_mode' IS NULL OR m.metadata->>'trigger_mode' != 'passive_sync')
ORDER BY COALESCE(bp.depth, 2147483647) DESC, COALESCE(m.branch_seq, 9223372036854775807) ASC, m.created_at ASC
`

type ListActiveMessagesSinceBySessionParams struct {
	SessionID pgtype.UUID        `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ListActiveMessagesSinceBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CompactID               pgtype.UUID        `json:"compact_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListActiveMessagesSinceBySession(ctx context.Context, arg ListActiveMessagesSinceBySessionParams) ([]ListActiveMessagesSinceBySessionRow, error) {
	rows, err := q.db.Query(ctx, listActiveMessagesSinceBySession, arg.SessionID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMessagesSinceBySessionRow
	for rows.Next() {
		var i ListActiveMessagesSinceBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CompactID,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
WHERE m.bot_id = $1
ORDER BY m.created_at ASC
LIMIT 10000
`

type ListMessagesRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessages(ctx context.Context, botID pgtype.UUID) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfterBySession = `-- name: ListMessagesAfterBySession :many
WITH RECURSIVE branch_path AS (
  SELECT b.id AS branch_id, b.parent_branch_id, NULL::BIGINT AS max_seq, 0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(s.active_branch_id, (
    SELECT rb.id FROM bot_session_branches rb
    WHERE rb.session_id = s.id AND rb.parent_branch_id IS NULL AND rb.fork_from_message_id IS NULL
    ORDER BY rb.created_at ASC LIMIT 1
  ))
  WHERE s.id = $1
  UNION ALL
  SELECT parent.id, parent.parent_branch_id, child.fork_from_seq, bp.depth + 1
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND m.created_at > $2
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
ORDER BY COALESCE(bp.depth, 2147483647) DESC, COALESCE(m.branch_seq, 9223372036854775807) ASC, m.created_at ASC
LIMIT $3
`

type ListMessagesAfterBySessionParams struct {
	SessionID pgtype.UUID        `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MaxCount  int32              `json:"max_count"`
}

type ListMessagesAfterBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesAfterBySession(ctx context.Context, arg ListMessagesAfterBySessionParams) ([]ListMessagesAfterBySessionRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfterBySession, arg.SessionID, arg.CreatedAt, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesAfterBySessionRow
	for rows.Next() {
		var i ListMessagesAfterBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
WHERE m.bot_id = $1
  AND m.created_at < $2
ORDER BY m.created_at DESC
LIMIT $3
`

type ListMessagesBeforeParams struct {
	BotID     pgtype.UUID        `json:"bot_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MaxCount  int32              `json:"max_count"`
}

type ListMessagesBeforeRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.BotID, arg.CreatedAt, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesBeforeRow
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBeforeBySession = `-- name: ListMessagesBeforeBySession :many
WITH RECURSIVE branch_path AS (
  SELECT b.id AS branch_id, b.parent_branch_id, NULL::BIGINT AS max_seq, 0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(s.active_branch_id, (
    SELECT rb.id FROM bot_session_branches rb
    WHERE rb.session_id = s.id AND rb.parent_branch_id IS NULL AND rb.fork_from_message_id IS NULL
    ORDER BY rb.created_at ASC LIMIT 1
  ))
  WHERE s.id = $1
  UNION ALL
  SELECT parent.id, parent.parent_branch_id, child.fork_from_seq, bp.depth + 1
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND m.created_at < $2
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
ORDER BY COALESCE(bp.depth, -1) ASC, COALESCE(m.branch_seq, 0) DESC, m.created_at DESC
LIMIT $3
`

type ListMessagesBeforeBySessionParams struct {
	SessionID pgtype.UUID        `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MaxCount  int32              `json:"max_count"`
}

type ListMessagesBeforeBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesBeforeBySession(ctx context.Context, arg ListMessagesBeforeBySessionParams) ([]ListMessagesBeforeBySessionRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBeforeBySession, arg.SessionID, arg.CreatedAt, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesBeforeBySessionRow
	for rows.Next() {
		var i ListMessagesBeforeBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
WITH RECURSIVE branch_path AS (
  SELECT
    b.id AS branch_id,
    b.parent_branch_id,
    NULL::BIGINT AS max_seq,
    0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(
    s.active_branch_id,
    (
      SELECT rb.id
      FROM bot_session_branches rb
      WHERE rb.session_id = s.id
        AND rb.parent_branch_id IS NULL
        AND rb.fork_from_message_id IS NULL
      ORDER BY rb.created_at ASC
      LIMIT 1
    )
  )
  WHERE s.id = $1
  UNION ALL
  SELECT
    parent.id AS branch_id,
    parent.parent_branch_id,
    child.fork_from_seq AS max_seq,
    bp.depth + 1 AS depth
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
ORDER BY COALESCE(bp.depth, 2147483647) DESC, COALESCE(m.branch_seq, 9223372036854775807) ASC, m.created_at ASC
LIMIT 10000
`

type ListMessagesBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID pgtype.UUID) ([]ListMessagesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesBySessionRow
	for rows.Next() {
		var i ListMessagesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesLatest = `-- name: ListMessagesLatest :many
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
WHERE m.bot_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type ListMessagesLatestParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	MaxCount int32       `json:"max_count"`
}

type ListMessagesLatestRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesLatest(ctx context.Context, arg ListMessagesLatestParams) ([]ListMessagesLatestRow, error) {
	rows, err := q.db.Query(ctx, listMessagesLatest, arg.BotID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesLatestRow
	for rows.Next() {
		var i ListMessagesLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesLatestBySession = `-- name: ListMessagesLatestBySession :many
WITH RECURSIVE branch_path AS (
  SELECT b.id AS branch_id, b.parent_branch_id, NULL::BIGINT AS max_seq, 0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(s.active_branch_id, (
    SELECT rb.id FROM bot_session_branches rb
    WHERE rb.session_id = s.id AND rb.parent_branch_id IS NULL AND rb.fork_from_message_id IS NULL
    ORDER BY rb.created_at ASC LIMIT 1
  ))
  WHERE s.id = $1
  UNION ALL
  SELECT parent.id, parent.parent_branch_id, child.fork_from_seq, bp.depth + 1
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
ORDER BY COALESCE(bp.depth, -1) ASC, COALESCE(m.branch_seq, 0) DESC, m.created_at DESC
LIMIT $2
`

type ListMessagesLatestBySessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	MaxCount  int32       `json:"max_count"`
}

type ListMessagesLatestBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesLatestBySession(ctx context.Context, arg ListMessagesLatestBySessionParams) ([]ListMessagesLatestBySessionRow, error) {
	rows, err := q.db.Query(ctx, listMessagesLatestBySession, arg.SessionID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesLatestBySessionRow
	for rows.Next() {
		var i ListMessagesLatestBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesSince = `-- name: ListMessagesSince :many
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
WHERE m.bot_id = $1
  AND m.created_at >= $2
ORDER BY m.created_at ASC
`

type ListMessagesSinceParams struct {
	BotID     pgtype.UUID        `json:"bot_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ListMessagesSinceRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesSince(ctx context.Context, arg ListMessagesSinceParams) ([]ListMessagesSinceRow, error) {
	rows, err := q.db.Query(ctx, listMessagesSince, arg.BotID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesSinceRow
	for rows.Next() {
		var i ListMessagesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesSinceBySession = `-- name: ListMessagesSinceBySession :many
WITH RECURSIVE branch_path AS (
  SELECT b.id AS branch_id, b.parent_branch_id, NULL::BIGINT AS max_seq, 0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(s.active_branch_id, (
    SELECT rb.id FROM bot_session_branches rb
    WHERE rb.session_id = s.id AND rb.parent_branch_id IS NULL AND rb.fork_from_message_id IS NULL
    ORDER BY rb.created_at ASC LIMIT 1
  ))
  WHERE s.id = $1
  UNION ALL
  SELECT parent.id, parent.parent_branch_id, child.fork_from_seq, bp.depth + 1
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND m.created_at >= $2
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
ORDER BY COALESCE(bp.depth, 2147483647) DESC, COALESCE(m.branch_seq, 9223372036854775807) ASC, m.created_at ASC
`

type ListMessagesSinceBySessionParams struct {
	SessionID pgtype.UUID        `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ListMessagesSinceBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListMessagesSinceBySession(ctx context.Context, arg ListMessagesSinceBySessionParams) ([]ListMessagesSinceBySessionRow, error) {
	rows, err := q.db.Query(ctx, listMessagesSinceBySession, arg.SessionID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesSinceBySessionRow
	for rows.Next() {
		var i ListMessagesSinceBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservedConversationsByChannelIdentity = `-- name: ListObservedConversationsByChannelIdentity :many
WITH observed_routes AS (
  SELECT
    s.route_id,
    MAX(m.created_at)::timestamptz AS last_observed_at
  FROM bot_history_messages m
  JOIN bot_sessions s ON s.id = m.session_id
  WHERE m.bot_id = $1
    AND m.sender_channel_identity_id = $2::uuid
    AND s.route_id IS NOT NULL
  GROUP BY s.route_id
)
SELECT
  r.id AS route_id,
  r.channel_type AS channel,
  CASE
    WHEN LOWER(COALESCE(r.conversation_type, '')) IN ('thread', 'topic') THEN 'thread'
    WHEN LOWER(COALESCE(r.conversation_type, '')) IN ('p2p', 'private', 'direct', 'dm') THEN 'private'
    ELSE 'group'
  END AS conversation_type,
  r.external_conversation_id AS conversation_id,
  COALESCE(r.external_thread_id, '') AS thread_id,
  COALESCE(
    NULLIF(TRIM(COALESCE(r.metadata->>'conversation_name', '')), ''),
    NULLIF(TRIM(COALESCE(r.metadata->>'conversation_handle', '')), ''),
    ''
  )::text AS conversation_name,
  COALESCE(NULLIF(TRIM(COALESCE(r.metadata->>'conversation_avatar_url', '')), ''), '')::text AS conversation_avatar_url,
  rr.last_observed_at
FROM observed_routes rr
JOIN bot_channel_routes r ON r.id = rr.route_id
GROUP BY
  r.id,
  r.channel_type,
  r.conversation_type,
  r.external_conversation_id,
  r.external_thread_id,
  r.metadata,
  rr.last_observed_at
ORDER BY rr.last_observed_at DESC
`

type ListObservedConversationsByChannelIdentityParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

type ListObservedConversationsByChannelIdentityRow struct {
	RouteID               pgtype.UUID        `json:"route_id"`
	Channel               string             `json:"channel"`
	ConversationType      string             `json:"conversation_type"`
	ConversationID        string             `json:"conversation_id"`
	ThreadID              string             `json:"thread_id"`
	ConversationName      string             `json:"conversation_name"`
	ConversationAvatarUrl string             `json:"conversation_avatar_url"`
	LastObservedAt        pgtype.Timestamptz `json:"last_observed_at"`
}

func (q *Queries) ListObservedConversationsByChannelIdentity(ctx context.Context, arg ListObservedConversationsByChannelIdentityParams) ([]ListObservedConversationsByChannelIdentityRow, error) {
	rows, err := q.db.Query(ctx, listObservedConversationsByChannelIdentity, arg.BotID, arg.ChannelIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObservedConversationsByChannelIdentityRow
	for rows.Next() {
		var i ListObservedConversationsByChannelIdentityRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Channel,
			&i.ConversationType,
			&i.ConversationID,
			&i.ThreadID,
			&i.ConversationName,
			&i.ConversationAvatarUrl,
			&i.LastObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservedConversationsByChannelType = `-- name: ListObservedConversationsByChannelType :many
WITH observed_routes AS (
  SELECT
    s.route_id,
    MAX(m.created_at)::timestamptz AS last_observed_at
  FROM bot_history_messages m
  JOIN bot_sessions s ON s.id = m.session_id
  JOIN bot_channel_routes r ON r.id = s.route_id
  WHERE m.bot_id = $1
    AND LOWER(TRIM(r.channel_type)) = LOWER(TRIM($2))
    AND s.route_id IS NOT NULL
  GROUP BY s.route_id
)
SELECT
  r.id AS route_id,
  r.channel_type AS channel,
  CASE
    WHEN LOWER(COALESCE(r.conversation_type, '')) IN ('thread', 'topic') THEN 'thread'
    WHEN LOWER(COALESCE(r.conversation_type, '')) IN ('p2p', 'private', 'direct', 'dm') THEN 'private'
    ELSE 'group'
  END AS conversation_type,
  r.external_conversation_id AS conversation_id,
  COALESCE(r.external_thread_id, '') AS thread_id,
  COALESCE(
    NULLIF(TRIM(COALESCE(r.metadata->>'conversation_name', '')), ''),
    NULLIF(TRIM(COALESCE(r.metadata->>'conversation_handle', '')), ''),
    ''
  )::text AS conversation_name,
  COALESCE(NULLIF(TRIM(COALESCE(r.metadata->>'conversation_avatar_url', '')), ''), '')::text AS conversation_avatar_url,
  rr.last_observed_at
FROM observed_routes rr
JOIN bot_channel_routes r ON r.id = rr.route_id
GROUP BY
  r.id,
  r.channel_type,
  r.conversation_type,
  r.external_conversation_id,
  r.external_thread_id,
  r.metadata,
  rr.last_observed_at
ORDER BY rr.last_observed_at DESC
`

type ListObservedConversationsByChannelTypeParams struct {
	BotID       pgtype.UUID `json:"bot_id"`
	ChannelType string      `json:"channel_type"`
}

type ListObservedConversationsByChannelTypeRow struct {
	RouteID               pgtype.UUID        `json:"route_id"`
	Channel               string             `json:"channel"`
	ConversationType      string             `json:"conversation_type"`
	ConversationID        string             `json:"conversation_id"`
	ThreadID              string             `json:"thread_id"`
	ConversationName      string             `json:"conversation_name"`
	ConversationAvatarUrl string             `json:"conversation_avatar_url"`
	LastObservedAt        pgtype.Timestamptz `json:"last_observed_at"`
}

// Routes on this platform type where the bot has seen at least one message (any sender).
func (q *Queries) ListObservedConversationsByChannelType(ctx context.Context, arg ListObservedConversationsByChannelTypeParams) ([]ListObservedConversationsByChannelTypeRow, error) {
	rows, err := q.db.Query(ctx, listObservedConversationsByChannelType, arg.BotID, arg.ChannelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObservedConversationsByChannelTypeRow
	for rows.Next() {
		var i ListObservedConversationsByChannelTypeRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Channel,
			&i.ConversationType,
			&i.ConversationID,
			&i.ThreadID,
			&i.ConversationName,
			&i.ConversationAvatarUrl,
			&i.LastObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionBranchPreviewMessages = `-- name: ListSessionBranchPreviewMessages :many
WITH user_turns AS (
  SELECT
    b.id AS branch_id,
    u.id AS user_id,
    u.branch_seq AS user_branch_seq,
    (
      SELECT MIN(next_user.branch_seq)
      FROM bot_history_messages next_user
      WHERE next_user.branch_id = u.branch_id
        AND next_user.role = 'user'
        AND next_user.branch_seq > u.branch_seq
    ) AS next_user_seq
  FROM bot_session_branches b
  JOIN bot_history_messages u ON u.branch_id = b.id
    AND u.role = 'user'
  WHERE b.session_id = $1
),
complete_turns AS (
  SELECT
    ut.branch_id,
    ut.user_id,
    (
      SELECT a.id
      FROM bot_history_messages a
      WHERE a.branch_id = ut.branch_id
        AND a.role = 'assistant'
        AND a.branch_seq > ut.user_branch_seq
        AND (ut.next_user_seq IS NULL OR a.branch_seq < ut.next_user_seq)
      ORDER BY a.branch_seq DESC, a.created_at DESC
      LIMIT 1
    ) AS assistant_id,
    ut.user_branch_seq
  FROM user_turns ut
),
targets AS (
  SELECT ct.branch_id, ct.user_id, ct.assistant_id
  FROM complete_turns ct
  WHERE ct.assistant_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1
      FROM complete_turns earlier
      WHERE earlier.branch_id = ct.branch_id
        AND earlier.assistant_id IS NOT NULL
        AND earlier.user_branch_seq < ct.user_branch_seq
    )
)
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  t.branch_id AS branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.sender_account_user_id AS sender_user_id,
  m.source_message_id AS external_message_id,
  m.source_reply_to_message_id,
  m.role,
  m.content,
  m.metadata,
  m.usage,
  m.event_id,
  m.display_text,
  m.created_at,
  ci.display_name AS sender_display_name,
  ci.avatar_url AS sender_avatar_url,
  s.channel_type AS platform
FROM targets t
JOIN bot_history_messages m ON m.id IN (t.user_id, t.assistant_id)
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
ORDER BY m.branch_id, m.branch_seq ASC, m.created_at ASC
`

type ListSessionBranchPreviewMessagesRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderUserID            pgtype.UUID        `json:"sender_user_id"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	Usage                   []byte             `json:"usage"`
	EventID                 pgtype.UUID        `json:"event_id"`
	DisplayText             pgtype.Text        `json:"display_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	SenderAvatarUrl         pgtype.Text        `json:"sender_avatar_url"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) ListSessionBranchPreviewMessages(ctx context.Context, sessionID pgtype.UUID) ([]ListSessionBranchPreviewMessagesRow, error) {
	rows, err := q.db.Query(ctx, listSessionBranchPreviewMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionBranchPreviewMessagesRow
	for rows.Next() {
		var i ListSessionBranchPreviewMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.SenderUserID,
			&i.ExternalMessageID,
			&i.SourceReplyToMessageID,
			&i.Role,
			&i.Content,
			&i.Metadata,
			&i.Usage,
			&i.EventID,
			&i.DisplayText,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionBranchTurnMessages = `-- name: ListSessionBranchTurnMessages :many
WITH user_turns AS (
  SELECT
    b.created_at AS branch_created_at,
    u.id AS user_id,
    u.bot_id AS user_bot_id,
    u.session_id AS user_session_id,
    u.branch_id,
    u.branch_seq AS user_branch_seq,
    u.content AS user_content,
    u.display_text AS user_display_text,
    u.created_at AS user_created_at,
    (
      SELECT MIN(next_user.branch_seq)
      FROM bot_history_messages next_user
      WHERE next_user.branch_id = u.branch_id
        AND next_user.role = 'user'
        AND next_user.branch_seq > u.branch_seq
    ) AS next_user_seq
  FROM bot_session_branches b
  JOIN bot_history_messages u ON u.branch_id = b.id
    AND u.role = 'user'
  WHERE b.session_id = $1
),
complete_turns AS (
  SELECT
    ut.branch_created_at, ut.user_id, ut.user_bot_id, ut.user_session_id, ut.branch_id, ut.user_branch_seq, ut.user_content, ut.user_display_text, ut.user_created_at, ut.next_user_seq,
    (
      SELECT a.id
      FROM bot_history_messages a
      WHERE a.branch_id = ut.branch_id
        AND a.role = 'assistant'
        AND a.branch_seq > ut.user_branch_seq
        AND (ut.next_user_seq IS NULL OR a.branch_seq < ut.next_user_seq)
      ORDER BY a.branch_seq DESC, a.created_at DESC
      LIMIT 1
    ) AS assistant_id
  FROM user_turns ut
)
SELECT
  a.id AS assistant_id,
  a.bot_id,
  a.session_id,
  a.branch_id,
  a.branch_seq,
  a.content AS assistant_content,
  a.display_text AS assistant_display_text,
  a.created_at AS assistant_created_at,
  ct.user_id,
  ct.user_content,
  ct.user_display_text,
  ct.user_created_at
FROM complete_turns ct
JOIN bot_history_messages a ON a.id = ct.assistant_id
ORDER BY ct.branch_created_at ASC, a.branch_seq ASC, a.created_at ASC
`

type ListSessionBranchTurnMessagesRow struct {
	AssistantID          pgtype.UUID        `json:"assistant_id"`
	BotID                pgtype.UUID        `json:"bot_id"`
	SessionID            pgtype.UUID        `json:"session_id"`
	BranchID             pgtype.UUID        `json:"branch_id"`
	BranchSeq            pgtype.Int8        `json:"branch_seq"`
	AssistantContent     []byte             `json:"assistant_content"`
	AssistantDisplayText pgtype.Text        `json:"assistant_display_text"`
	AssistantCreatedAt   pgtype.Timestamptz `json:"assistant_created_at"`
	UserID               pgtype.UUID        `json:"user_id"`
	UserContent          []byte             `json:"user_content"`
	UserDisplayText      pgtype.Text        `json:"user_display_text"`
	UserCreatedAt        pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ListSessionBranchTurnMessages(ctx context.Context, sessionID pgtype.UUID) ([]ListSessionBranchTurnMessagesRow, error) {
	rows, err := q.db.Query(ctx, listSessionBranchTurnMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionBranchTurnMessagesRow
	for rows.Next() {
		var i ListSessionBranchTurnMessagesRow
		if err := rows.Scan(
			&i.AssistantID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.AssistantContent,
			&i.AssistantDisplayText,
			&i.AssistantCreatedAt,
			&i.UserID,
			&i.UserContent,
			&i.UserDisplayText,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionBranches = `-- name: ListSessionBranches :many
SELECT
  b.id,
  b.session_id,
  b.parent_branch_id,
  b.fork_from_message_id,
  b.fork_from_seq,
  b.title,
  b.created_at,
  b.updated_at,
  s.active_branch_id
FROM bot_session_branches b
JOIN bot_sessions s ON s.id = b.session_id
WHERE b.session_id = $1
ORDER BY b.created_at ASC, b.id ASC
`

type ListSessionBranchesRow struct {
	ID                pgtype.UUID        `json:"id"`
	SessionID         pgtype.UUID        `json:"session_id"`
	ParentBranchID    pgtype.UUID        `json:"parent_branch_id"`
	ForkFromMessageID pgtype.UUID        `json:"fork_from_message_id"`
	ForkFromSeq       pgtype.Int8        `json:"fork_from_seq"`
	Title             pgtype.Text        `json:"title"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ActiveBranchID    pgtype.UUID        `json:"active_branch_id"`
}

func (q *Queries) ListSessionBranches(ctx context.Context, sessionID pgtype.UUID) ([]ListSessionBranchesRow, error) {
	rows, err := q.db.Query(ctx, listSessionBranches, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionBranchesRow
	for rows.Next() {
		var i ListSessionBranchesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentBranchID,
			&i.ForkFromMessageID,
			&i.ForkFromSeq,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveBranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncompactedMessagesBySession = `-- name: ListUncompactedMessagesBySession :many
WITH RECURSIVE branch_path AS (
  SELECT b.id AS branch_id, b.parent_branch_id, NULL::BIGINT AS max_seq, 0 AS depth
  FROM bot_sessions s
  JOIN bot_session_branches b ON b.id = COALESCE(s.active_branch_id, (
    SELECT rb.id FROM bot_session_branches rb
    WHERE rb.session_id = s.id AND rb.parent_branch_id IS NULL AND rb.fork_from_message_id IS NULL
    ORDER BY rb.created_at ASC LIMIT 1
  ))
  WHERE s.id = $1
  UNION ALL
  SELECT parent.id, parent.parent_branch_id, child.fork_from_seq, bp.depth + 1
  FROM branch_path bp
  JOIN bot_session_branches child ON child.id = bp.branch_id
  JOIN bot_session_branches parent ON parent.id = child.parent_branch_id
)
SELECT m.id, m.bot_id, m.session_id, m.role, m.content, m.usage, m.sender_channel_identity_id, m.compact_id, m.created_at
FROM bot_history_messages m
LEFT JOIN branch_path bp ON bp.branch_id = m.branch_id
WHERE m.session_id = $1
  AND m.compact_id IS NULL
  AND (
    m.branch_id IS NULL
    OR (bp.branch_id IS NOT NULL AND (bp.max_seq IS NULL OR m.branch_seq <= bp.max_seq))
  )
ORDER BY COALESCE(bp.depth, 2147483647) DESC, COALESCE(m.branch_seq, 9223372036854775807) ASC, m.created_at ASC
`

type ListUncompactedMessagesBySessionRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Usage                   []byte             `json:"usage"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	CompactID               pgtype.UUID        `json:"compact_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUncompactedMessagesBySession(ctx context.Context, sessionID pgtype.UUID) ([]ListUncompactedMessagesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listUncompactedMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUncompactedMessagesBySessionRow
	for rows.Next() {
		var i ListUncompactedMessagesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Usage,
			&i.SenderChannelIdentityID,
			&i.CompactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesCompacted = `-- name: MarkMessagesCompacted :exec
UPDATE bot_history_messages
SET compact_id = $1
WHERE id = ANY($2::uuid[])
`

type MarkMessagesCompactedParams struct {
	CompactID pgtype.UUID   `json:"compact_id"`
	Column2   []pgtype.UUID `json:"column_2"`
}

func (q *Queries) MarkMessagesCompacted(ctx context.Context, arg MarkMessagesCompactedParams) error {
	_, err := q.db.Exec(ctx, markMessagesCompacted, arg.CompactID, arg.Column2)
	return err
}

const searchMessages = `-- name: SearchMessages :many
SELECT
  m.id,
  m.bot_id,
  m.session_id,
  m.branch_id,
  m.branch_seq,
  m.sender_channel_identity_id,
  m.role,
  m.content,
  m.created_at,
  ci.display_name AS sender_display_name,
  s.channel_type AS platform
FROM bot_history_messages m
LEFT JOIN channel_identities ci ON ci.id = m.sender_channel_identity_id
LEFT JOIN bot_sessions s ON s.id = m.session_id
WHERE m.bot_id = $1
  AND ($2::uuid IS NULL OR m.session_id = $2::uuid)
  AND ($3::uuid IS NULL OR m.sender_channel_identity_id = $3::uuid)
  AND ($4::timestamptz IS NULL OR m.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR m.created_at <= $5::timestamptz)
  AND ($6::text IS NULL OR m.role = $6::text)
  AND ($7::text IS NULL OR (
    CASE
      WHEN jsonb_typeof(m.content->'content') = 'string'
        THEN m.content->>'content'
      WHEN jsonb_typeof(m.content->'content') = 'array'
        THEN (SELECT COALESCE(string_agg(elem->>'text', ' '), '')
              FROM jsonb_array_elements(m.content->'content') AS elem
              WHERE elem->>'type' = 'text')
      ELSE ''
    END
  ) ILIKE '%' || $7::text || '%')
ORDER BY m.created_at DESC
LIMIT $8
`

type SearchMessagesParams struct {
	BotID     pgtype.UUID        `json:"bot_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	ContactID pgtype.UUID        `json:"contact_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Role      pgtype.Text        `json:"role"`
	Keyword   pgtype.Text        `json:"keyword"`
	MaxCount  int32              `json:"max_count"`
}

type SearchMessagesRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	BranchID                pgtype.UUID        `json:"branch_id"`
	BranchSeq               pgtype.Int8        `json:"branch_seq"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SenderDisplayName       pgtype.Text        `json:"sender_display_name"`
	Platform                pgtype.Text        `json:"platform"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.BotID,
		arg.SessionID,
		arg.ContactID,
		arg.StartTime,
		arg.EndTime,
		arg.Role,
		arg.Keyword,
		arg.MaxCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.BranchID,
			&i.BranchSeq,
			&i.SenderChannelIdentityID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveSessionBranch = `-- name: SetActiveSessionBranch :exec
UPDATE bot_sessions
SET active_branch_id = $1,
    updated_at = now()
WHERE bot_sessions.id = $2
  AND EXISTS (
    SELECT 1
    FROM bot_session_branches b
    WHERE b.id = $1
      AND b.session_id = $2
  )
`

type SetActiveSessionBranchParams struct {
	BranchID  pgtype.UUID `json:"branch_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) SetActiveSessionBranch(ctx context.Context, arg SetActiveSessionBranchParams) error {
	_, err := q.db.Exec(ctx, setActiveSessionBranch, arg.BranchID, arg.SessionID)
	return err
}
