// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedule (
  name, description, pattern, max_calls, enabled, command, bot_id,
  run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8,
  $9::uuid,
  $10::text,
  $11::uuid,
  $12::text,
  $13::uuid,
  $14::text,
  $15::text,
  $16::uuid
)
RETURNING id, name, description, pattern, max_calls, current_calls, created_at, updated_at, enabled, command, bot_id, run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id, team_id
`

type CreateScheduleParams struct {
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	Pattern         string      `json:"pattern"`
	MaxCalls        pgtype.Int4 `json:"max_calls"`
	Enabled         bool        `json:"enabled"`
	Command         string      `json:"command"`
	BotID           pgtype.UUID `json:"bot_id"`
	RunTarget       string      `json:"run_target"`
	TargetSessionID pgtype.UUID `json:"target_session_id"`
	RuntimeType     pgtype.Text `json:"runtime_type"`
	BotAgentID      pgtype.UUID `json:"bot_agent_id"`
	AcpAgentID      pgtype.Text `json:"acp_agent_id"`
	ModelID         pgtype.UUID `json:"model_id"`
	AcpModelID      pgtype.Text `json:"acp_model_id"`
	ReasoningEffort pgtype.Text `json:"reasoning_effort"`
	WorkdirID       pgtype.UUID `json:"workdir_id"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.Name,
		arg.Description,
		arg.Pattern,
		arg.MaxCalls,
		arg.Enabled,
		arg.Command,
		arg.BotID,
		arg.RunTarget,
		arg.TargetSessionID,
		arg.RuntimeType,
		arg.BotAgentID,
		arg.AcpAgentID,
		arg.ModelID,
		arg.AcpModelID,
		arg.ReasoningEffort,
		arg.WorkdirID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Pattern,
		&i.MaxCalls,
		&i.CurrentCalls,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Command,
		&i.BotID,
		&i.RunTarget,
		&i.TargetSessionID,
		&i.RuntimeType,
		&i.BotAgentID,
		&i.AcpAgentID,
		&i.ModelID,
		&i.AcpModelID,
		&i.ReasoningEffort,
		&i.WorkdirID,
		&i.TeamID,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedule
WHERE team_id = public.memoh_current_team_id() AND id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const disableSchedule = `-- name: DisableSchedule :one
UPDATE schedule
SET enabled = false,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $1
RETURNING id, name, description, pattern, max_calls, current_calls, created_at, updated_at, enabled, command, bot_id, run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id, team_id
`

func (q *Queries) DisableSchedule(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, disableSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Pattern,
		&i.MaxCalls,
		&i.CurrentCalls,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Command,
		&i.BotID,
		&i.RunTarget,
		&i.TargetSessionID,
		&i.RuntimeType,
		&i.BotAgentID,
		&i.AcpAgentID,
		&i.ModelID,
		&i.AcpModelID,
		&i.ReasoningEffort,
		&i.WorkdirID,
		&i.TeamID,
	)
	return i, err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, name, description, pattern, max_calls, current_calls, created_at, updated_at, enabled, command, bot_id, run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id, team_id
FROM schedule
WHERE team_id = public.memoh_current_team_id() AND id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Pattern,
		&i.MaxCalls,
		&i.CurrentCalls,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Command,
		&i.BotID,
		&i.RunTarget,
		&i.TargetSessionID,
		&i.RuntimeType,
		&i.BotAgentID,
		&i.AcpAgentID,
		&i.ModelID,
		&i.AcpModelID,
		&i.ReasoningEffort,
		&i.WorkdirID,
		&i.TeamID,
	)
	return i, err
}

const incrementScheduleCalls = `-- name: IncrementScheduleCalls :one
UPDATE schedule
SET current_calls = current_calls + 1,
    enabled = CASE
      WHEN max_calls IS NOT NULL AND current_calls + 1 >= max_calls THEN false
      ELSE enabled
    END,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $1
RETURNING id, name, description, pattern, max_calls, current_calls, created_at, updated_at, enabled, command, bot_id, run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id, team_id
`

func (q *Queries) IncrementScheduleCalls(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, incrementScheduleCalls, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Pattern,
		&i.MaxCalls,
		&i.CurrentCalls,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Command,
		&i.BotID,
		&i.RunTarget,
		&i.TargetSessionID,
		&i.RuntimeType,
		&i.BotAgentID,
		&i.AcpAgentID,
		&i.ModelID,
		&i.AcpModelID,
		&i.ReasoningEffort,
		&i.WorkdirID,
		&i.TeamID,
	)
	return i, err
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, name, description, pattern, max_calls, current_calls, created_at, updated_at, enabled, command, bot_id, run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id, team_id
FROM schedule
WHERE team_id = public.memoh_current_team_id() AND enabled = true
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Pattern,
			&i.MaxCalls,
			&i.CurrentCalls,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.Command,
			&i.BotID,
			&i.RunTarget,
			&i.TargetSessionID,
			&i.RuntimeType,
			&i.BotAgentID,
			&i.AcpAgentID,
			&i.ModelID,
			&i.AcpModelID,
			&i.ReasoningEffort,
			&i.WorkdirID,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByBot = `-- name: ListSchedulesByBot :many
SELECT id, name, description, pattern, max_calls, current_calls, created_at, updated_at, enabled, command, bot_id, run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id, team_id
FROM schedule
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSchedulesByBot(ctx context.Context, botID pgtype.UUID) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Pattern,
			&i.MaxCalls,
			&i.CurrentCalls,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.Command,
			&i.BotID,
			&i.RunTarget,
			&i.TargetSessionID,
			&i.RuntimeType,
			&i.BotAgentID,
			&i.AcpAgentID,
			&i.ModelID,
			&i.AcpModelID,
			&i.ReasoningEffort,
			&i.WorkdirID,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedule
SET name = $2,
    description = $3,
    pattern = $4,
    max_calls = $5,
    enabled = $6,
    command = $7,
    run_target = $8,
    target_session_id = $9::uuid,
    runtime_type = $10::text,
    bot_agent_id = $11::uuid,
    acp_agent_id = $12::text,
    model_id = $13::uuid,
    acp_model_id = $14::text,
    reasoning_effort = $15::text,
    workdir_id = $16::uuid,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $1
RETURNING id, name, description, pattern, max_calls, current_calls, created_at, updated_at, enabled, command, bot_id, run_target, target_session_id, runtime_type, bot_agent_id, acp_agent_id, model_id, acp_model_id, reasoning_effort, workdir_id, team_id
`

type UpdateScheduleParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	Pattern         string      `json:"pattern"`
	MaxCalls        pgtype.Int4 `json:"max_calls"`
	Enabled         bool        `json:"enabled"`
	Command         string      `json:"command"`
	RunTarget       string      `json:"run_target"`
	TargetSessionID pgtype.UUID `json:"target_session_id"`
	RuntimeType     pgtype.Text `json:"runtime_type"`
	BotAgentID      pgtype.UUID `json:"bot_agent_id"`
	AcpAgentID      pgtype.Text `json:"acp_agent_id"`
	ModelID         pgtype.UUID `json:"model_id"`
	AcpModelID      pgtype.Text `json:"acp_model_id"`
	ReasoningEffort pgtype.Text `json:"reasoning_effort"`
	WorkdirID       pgtype.UUID `json:"workdir_id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Pattern,
		arg.MaxCalls,
		arg.Enabled,
		arg.Command,
		arg.RunTarget,
		arg.TargetSessionID,
		arg.RuntimeType,
		arg.BotAgentID,
		arg.AcpAgentID,
		arg.ModelID,
		arg.AcpModelID,
		arg.ReasoningEffort,
		arg.WorkdirID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Pattern,
		&i.MaxCalls,
		&i.CurrentCalls,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Command,
		&i.BotID,
		&i.RunTarget,
		&i.TargetSessionID,
		&i.RuntimeType,
		&i.BotAgentID,
		&i.AcpAgentID,
		&i.ModelID,
		&i.AcpModelID,
		&i.ReasoningEffort,
		&i.WorkdirID,
		&i.TeamID,
	)
	return i, err
}
