// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO bot_sessions (
  bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, parent_session_id, created_by_user_id
)
VALUES (
  $1,
  $2::uuid,
  $3::text,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10::uuid,
  $11::uuid
)
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	RouteID         pgtype.UUID `json:"route_id"`
	ChannelType     pgtype.Text `json:"channel_type"`
	Type            string      `json:"type"`
	SessionMode     string      `json:"session_mode"`
	RuntimeType     string      `json:"runtime_type"`
	RuntimeMetadata []byte      `json:"runtime_metadata"`
	Title           string      `json:"title"`
	Metadata        []byte      `json:"metadata"`
	ParentSessionID pgtype.UUID `json:"parent_session_id"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.BotID,
		arg.RouteID,
		arg.ChannelType,
		arg.Type,
		arg.SessionMode,
		arg.RuntimeType,
		arg.RuntimeMetadata,
		arg.Title,
		arg.Metadata,
		arg.ParentSessionID,
		arg.CreatedByUserID,
	)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSessionDiscussCursorsByBot = `-- name: DeleteSessionDiscussCursorsByBot :exec
DELETE FROM bot_session_discuss_cursors
WHERE session_id IN (
  SELECT id
  FROM bot_sessions
  WHERE bot_id = $1
)
`

func (q *Queries) DeleteSessionDiscussCursorsByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionDiscussCursorsByBot, botID)
	return err
}

const forkSessionFromAssistantMessage = `-- name: ForkSessionFromAssistantMessage :one
WITH source_session AS (
  SELECT s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata, s.next_turn_position, s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at
  FROM bot_sessions s
  WHERE s.id = $1
    AND s.bot_id = $2
    AND s.type = 'chat'
    AND s.deleted_at IS NULL
),
target_turn AS (
  SELECT
    vm.turn_id AS id,
    vm.turn_position AS position,
    vm.id AS message_id
  FROM source_session s
  JOIN bot_visible_history_messages vm ON vm.session_id = s.id
    AND vm.id = $3
    AND vm.role = 'assistant'
    AND vm.turn_id IS NOT NULL
    AND vm.turn_position IS NOT NULL
  LIMIT 1
),
created_session AS (
  INSERT INTO bot_sessions (
    bot_id,
    channel_type,
    type,
    session_mode,
    runtime_type,
    runtime_metadata,
    title,
    metadata,
    created_by_user_id
  )
  SELECT
    s.bot_id,
    s.channel_type,
    s.type,
    s.session_mode,
    s.runtime_type,
    s.runtime_metadata,
    $4,
    $5,
    $6::uuid
  FROM source_session s
  JOIN target_turn tt ON true
  RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
),
copy_messages AS (
  SELECT
    vm.id AS old_message_id,
    gen_random_uuid() AS new_message_id,
    vm.sender_channel_identity_id,
    vm.sender_account_user_id,
    vm.source_message_id,
    vm.source_reply_to_message_id,
    vm.role,
    vm.content,
    vm.metadata,
    vm.usage,
    vm.session_mode,
    vm.runtime_type,
    vm.model_id,
    vm.display_text,
    vm.turn_id AS old_turn_id,
    vm.turn_position,
    vm.turn_message_seq,
    vm.created_at
  FROM bot_visible_history_messages vm
  JOIN target_turn tt ON (
    vm.turn_position < tt.position
    OR vm.turn_position = tt.position
  )
  WHERE vm.session_id = $1
  ORDER BY vm.turn_position ASC, vm.turn_message_seq ASC, vm.created_at ASC, vm.id ASC
),
copy_turns AS (
  SELECT
    cm.old_turn_id,
    gen_random_uuid() AS new_turn_id,
    cm.turn_position AS old_position,
    ROW_NUMBER() OVER (ORDER BY cm.turn_position ASC)::bigint AS new_position
  FROM (
    SELECT DISTINCT old_turn_id, turn_position
    FROM copy_messages
  ) cm
  ORDER BY cm.turn_position ASC
),
inserted_messages AS (
  INSERT INTO bot_history_messages (
    id,
    bot_id,
    session_id,
    sender_channel_identity_id,
    sender_account_user_id,
    source_message_id,
    source_reply_to_message_id,
    role,
    content,
    metadata,
    usage,
    session_mode,
    runtime_type,
    model_id,
    display_text,
    turn_id,
    turn_position,
    turn_message_seq,
    turn_visible,
    created_at
  )
  SELECT
    cm.new_message_id,
    cs.bot_id,
    cs.id,
    cm.sender_channel_identity_id,
    cm.sender_account_user_id,
    cm.source_message_id,
    cm.source_reply_to_message_id,
    cm.role,
    cm.content,
    cm.metadata,
    cm.usage,
    cm.session_mode,
    cm.runtime_type,
    cm.model_id,
    cm.display_text,
    ct.new_turn_id,
    ct.new_position,
    cm.turn_message_seq,
    true,
    cm.created_at
  FROM copy_messages cm
  JOIN copy_turns ct ON ct.old_turn_id = cm.old_turn_id
  CROSS JOIN created_session cs
  RETURNING id
),
copy_message_counts AS (
  SELECT count(*) AS count FROM copy_messages
),
inserted_message_counts AS (
  SELECT count(*) AS count FROM inserted_messages
),
next_turn_position AS (
  SELECT COALESCE(MAX(new_position), 0) + 1 AS value
  FROM copy_turns
),
copied_assets AS (
  INSERT INTO bot_history_message_assets (
    message_id,
    role,
    ordinal,
    content_hash,
    name,
    metadata
  )
  SELECT
    cm.new_message_id,
    a.role,
    a.ordinal,
    a.content_hash,
    a.name,
    a.metadata
  FROM bot_history_message_assets a
  JOIN copy_messages cm ON cm.old_message_id = a.message_id
  JOIN inserted_messages im ON im.id = cm.new_message_id
  RETURNING id
),
fork_anchor_message AS (
  SELECT assistant_message.new_message_id
  FROM copy_turns ct
  JOIN target_turn tt ON tt.id = ct.old_turn_id
  JOIN copy_messages assistant_message ON assistant_message.old_message_id = ct.assistant_message_id
  LIMIT 1
),
updated_session AS (
  UPDATE bot_sessions s
  SET next_turn_position = ntp.value,
      metadata = jsonb_set(
        s.metadata,
        '{forked_from}',
        COALESCE(s.metadata->'forked_from', '{}'::jsonb) || jsonb_build_object('fork_message_id', fam.new_message_id::text),
        true
      )
  FROM created_session cs
  JOIN fork_anchor_message fam ON true
  CROSS JOIN next_turn_position ntp
  WHERE s.id = cs.id
  RETURNING s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata, s.next_turn_position, s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at
)
SELECT us.id, us.bot_id, us.route_id, us.channel_type, us.type, us.session_mode, us.runtime_type, us.runtime_metadata, us.title, us.metadata, us.next_turn_position, us.parent_session_id, us.created_by_user_id, us.created_at, us.updated_at, us.deleted_at
FROM updated_session us
CROSS JOIN (SELECT count(*) AS copied_asset_count FROM copied_assets) copied_asset_counts
CROSS JOIN copy_message_counts
CROSS JOIN inserted_message_counts
WHERE EXISTS (SELECT 1 FROM copy_turns)
  AND inserted_message_counts.count = copy_message_counts.count
`

type ForkSessionFromAssistantMessageParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	BotID           pgtype.UUID `json:"bot_id"`
	MessageID       pgtype.UUID `json:"message_id"`
	Title           string      `json:"title"`
	Metadata        []byte      `json:"metadata"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

type ForkSessionFromAssistantMessageRow struct {
	ID               pgtype.UUID        `json:"id"`
	BotID            pgtype.UUID        `json:"bot_id"`
	RouteID          pgtype.UUID        `json:"route_id"`
	ChannelType      pgtype.Text        `json:"channel_type"`
	Type             string             `json:"type"`
	SessionMode      string             `json:"session_mode"`
	RuntimeType      string             `json:"runtime_type"`
	RuntimeMetadata  []byte             `json:"runtime_metadata"`
	Title            string             `json:"title"`
	Metadata         []byte             `json:"metadata"`
	NextTurnPosition int64              `json:"next_turn_position"`
	ParentSessionID  pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID  pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ForkSessionFromAssistantMessage(ctx context.Context, arg ForkSessionFromAssistantMessageParams) (ForkSessionFromAssistantMessageRow, error) {
	row := q.db.QueryRow(ctx, forkSessionFromAssistantMessage,
		arg.SessionID,
		arg.BotID,
		arg.MessageID,
		arg.Title,
		arg.Metadata,
		arg.CreatedByUserID,
	)
	var i ForkSessionFromAssistantMessageRow
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveSessionForRoute = `-- name: GetActiveSessionForRoute :one
SELECT s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata, s.next_turn_position, s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at
FROM bot_sessions s
JOIN bot_channel_routes r ON r.active_session_id = s.id
WHERE r.id = $1
  AND s.deleted_at IS NULL
`

func (q *Queries) GetActiveSessionForRoute(ctx context.Context, routeID pgtype.UUID) (BotSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionForRoute, routeID)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
FROM bot_sessions
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (BotSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionDiscussCursor = `-- name: GetSessionDiscussCursor :one
SELECT session_id, scope_key, route_id, source, consumed_cursor, updated_at
FROM bot_session_discuss_cursors
WHERE session_id = $1
  AND scope_key = $2
`

type GetSessionDiscussCursorParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ScopeKey  string      `json:"scope_key"`
}

func (q *Queries) GetSessionDiscussCursor(ctx context.Context, arg GetSessionDiscussCursorParams) (BotSessionDiscussCursor, error) {
	row := q.db.QueryRow(ctx, getSessionDiscussCursor, arg.SessionID, arg.ScopeKey)
	var i BotSessionDiscussCursor
	err := row.Scan(
		&i.SessionID,
		&i.ScopeKey,
		&i.RouteID,
		&i.Source,
		&i.ConsumedCursor,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionDiscussCursorsByBot = `-- name: ListSessionDiscussCursorsByBot :many
SELECT c.session_id, c.scope_key, c.route_id, c.source, c.consumed_cursor, c.updated_at
FROM bot_session_discuss_cursors c
JOIN bot_sessions s ON s.id = c.session_id
WHERE s.bot_id = $1
ORDER BY c.updated_at ASC, c.session_id ASC, c.scope_key ASC
`

func (q *Queries) ListSessionDiscussCursorsByBot(ctx context.Context, botID pgtype.UUID) ([]BotSessionDiscussCursor, error) {
	rows, err := q.db.Query(ctx, listSessionDiscussCursorsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSessionDiscussCursor
	for rows.Next() {
		var i BotSessionDiscussCursor
		if err := rows.Scan(
			&i.SessionID,
			&i.ScopeKey,
			&i.RouteID,
			&i.Source,
			&i.ConsumedCursor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBot = `-- name: ListSessionsByBot :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at,
  r.metadata AS route_metadata,
  r.conversation_type AS route_conversation_type
FROM bot_sessions s
LEFT JOIN bot_channel_routes r ON r.id = s.route_id
WHERE s.bot_id = $1
  AND s.deleted_at IS NULL
ORDER BY s.updated_at DESC
`

type ListSessionsByBotRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BotID                 pgtype.UUID        `json:"bot_id"`
	RouteID               pgtype.UUID        `json:"route_id"`
	ChannelType           pgtype.Text        `json:"channel_type"`
	Type                  string             `json:"type"`
	SessionMode           string             `json:"session_mode"`
	RuntimeType           string             `json:"runtime_type"`
	RuntimeMetadata       []byte             `json:"runtime_metadata"`
	Title                 string             `json:"title"`
	Metadata              []byte             `json:"metadata"`
	ParentSessionID       pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID       pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	RouteMetadata         []byte             `json:"route_metadata"`
	RouteConversationType pgtype.Text        `json:"route_conversation_type"`
}

func (q *Queries) ListSessionsByBot(ctx context.Context, botID pgtype.UUID) ([]ListSessionsByBotRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotRow
	for rows.Next() {
		var i ListSessionsByBotRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RouteMetadata,
			&i.RouteConversationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBotAndCreatedByUser = `-- name: ListSessionsByBotAndCreatedByUser :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at,
  r.metadata AS route_metadata,
  r.conversation_type AS route_conversation_type
FROM bot_sessions s
LEFT JOIN bot_channel_routes r ON r.id = s.route_id
WHERE s.bot_id = $1
  AND s.created_by_user_id = $2
  AND s.deleted_at IS NULL
ORDER BY s.updated_at DESC
`

type ListSessionsByBotAndCreatedByUserParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

type ListSessionsByBotAndCreatedByUserRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BotID                 pgtype.UUID        `json:"bot_id"`
	RouteID               pgtype.UUID        `json:"route_id"`
	ChannelType           pgtype.Text        `json:"channel_type"`
	Type                  string             `json:"type"`
	SessionMode           string             `json:"session_mode"`
	RuntimeType           string             `json:"runtime_type"`
	RuntimeMetadata       []byte             `json:"runtime_metadata"`
	Title                 string             `json:"title"`
	Metadata              []byte             `json:"metadata"`
	ParentSessionID       pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID       pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	RouteMetadata         []byte             `json:"route_metadata"`
	RouteConversationType pgtype.Text        `json:"route_conversation_type"`
}

func (q *Queries) ListSessionsByBotAndCreatedByUser(ctx context.Context, arg ListSessionsByBotAndCreatedByUserParams) ([]ListSessionsByBotAndCreatedByUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBotAndCreatedByUser, arg.BotID, arg.CreatedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotAndCreatedByUserRow
	for rows.Next() {
		var i ListSessionsByBotAndCreatedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RouteMetadata,
			&i.RouteConversationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBotAndCreatedByUserPaged = `-- name: ListSessionsByBotAndCreatedByUserPaged :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at,
  r.metadata AS route_metadata,
  r.conversation_type AS route_conversation_type
FROM bot_sessions s
LEFT JOIN bot_channel_routes r ON r.id = s.route_id
WHERE s.bot_id = $1
  AND s.created_by_user_id = $2
  AND s.deleted_at IS NULL
  AND s.type = ANY($3::text[])
  AND (
    NOT $4::bool
    OR s.parent_session_id = $5::uuid
  )
  AND (
    NOT $6::bool
    OR (s.updated_at, s.id) < ($7::timestamptz, $8::uuid)
  )
ORDER BY s.updated_at DESC, s.id DESC
LIMIT $9::int
`

type ListSessionsByBotAndCreatedByUserPagedParams struct {
	BotID            pgtype.UUID        `json:"bot_id"`
	CreatedByUserID  pgtype.UUID        `json:"created_by_user_id"`
	Types            []string           `json:"types"`
	UseParentSession bool               `json:"use_parent_session"`
	ParentSessionID  pgtype.UUID        `json:"parent_session_id"`
	UseCursor        bool               `json:"use_cursor"`
	CursorUpdatedAt  pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListSessionsByBotAndCreatedByUserPagedRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BotID                 pgtype.UUID        `json:"bot_id"`
	RouteID               pgtype.UUID        `json:"route_id"`
	ChannelType           pgtype.Text        `json:"channel_type"`
	Type                  string             `json:"type"`
	SessionMode           string             `json:"session_mode"`
	RuntimeType           string             `json:"runtime_type"`
	RuntimeMetadata       []byte             `json:"runtime_metadata"`
	Title                 string             `json:"title"`
	Metadata              []byte             `json:"metadata"`
	ParentSessionID       pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID       pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	RouteMetadata         []byte             `json:"route_metadata"`
	RouteConversationType pgtype.Text        `json:"route_conversation_type"`
}

func (q *Queries) ListSessionsByBotAndCreatedByUserPaged(ctx context.Context, arg ListSessionsByBotAndCreatedByUserPagedParams) ([]ListSessionsByBotAndCreatedByUserPagedRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBotAndCreatedByUserPaged,
		arg.BotID,
		arg.CreatedByUserID,
		arg.Types,
		arg.UseParentSession,
		arg.ParentSessionID,
		arg.UseCursor,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotAndCreatedByUserPagedRow
	for rows.Next() {
		var i ListSessionsByBotAndCreatedByUserPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RouteMetadata,
			&i.RouteConversationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByBotPaged = `-- name: ListSessionsByBotPaged :many
SELECT
  s.id, s.bot_id, s.route_id, s.channel_type, s.type, s.session_mode, s.runtime_type, s.runtime_metadata, s.title, s.metadata,
  s.parent_session_id, s.created_by_user_id, s.created_at, s.updated_at, s.deleted_at,
  r.metadata AS route_metadata,
  r.conversation_type AS route_conversation_type
FROM bot_sessions s
LEFT JOIN bot_channel_routes r ON r.id = s.route_id
WHERE s.bot_id = $1
  AND s.deleted_at IS NULL
  AND s.type = ANY($2::text[])
  AND (
    NOT $3::bool
    OR s.parent_session_id = $4::uuid
  )
  AND (
    NOT $5::bool
    OR (s.updated_at, s.id) < ($6::timestamptz, $7::uuid)
  )
ORDER BY s.updated_at DESC, s.id DESC
LIMIT $8::int
`

type ListSessionsByBotPagedParams struct {
	BotID            pgtype.UUID        `json:"bot_id"`
	Types            []string           `json:"types"`
	UseParentSession bool               `json:"use_parent_session"`
	ParentSessionID  pgtype.UUID        `json:"parent_session_id"`
	UseCursor        bool               `json:"use_cursor"`
	CursorUpdatedAt  pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	LimitCount       int32              `json:"limit_count"`
}

type ListSessionsByBotPagedRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BotID                 pgtype.UUID        `json:"bot_id"`
	RouteID               pgtype.UUID        `json:"route_id"`
	ChannelType           pgtype.Text        `json:"channel_type"`
	Type                  string             `json:"type"`
	SessionMode           string             `json:"session_mode"`
	RuntimeType           string             `json:"runtime_type"`
	RuntimeMetadata       []byte             `json:"runtime_metadata"`
	Title                 string             `json:"title"`
	Metadata              []byte             `json:"metadata"`
	ParentSessionID       pgtype.UUID        `json:"parent_session_id"`
	CreatedByUserID       pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	RouteMetadata         []byte             `json:"route_metadata"`
	RouteConversationType pgtype.Text        `json:"route_conversation_type"`
}

// Cursor uses (updated_at, id) so pages stay stable when many rows share an
// updated_at. Callers always pass an explicit types filter; to opt out of
// filtering, pass every known type.
func (q *Queries) ListSessionsByBotPaged(ctx context.Context, arg ListSessionsByBotPagedParams) ([]ListSessionsByBotPagedRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByBotPaged,
		arg.BotID,
		arg.Types,
		arg.UseParentSession,
		arg.ParentSessionID,
		arg.UseCursor,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByBotPagedRow
	for rows.Next() {
		var i ListSessionsByBotPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RouteMetadata,
			&i.RouteConversationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByRoute = `-- name: ListSessionsByRoute :many
SELECT id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
FROM bot_sessions
WHERE route_id = $1
  AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSessionsByRoute(ctx context.Context, routeID pgtype.UUID) ([]BotSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSession
	for rows.Next() {
		var i BotSession
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.NextTurnPosition,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubagentSessionsByParent = `-- name: ListSubagentSessionsByParent :many
SELECT id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
FROM bot_sessions
WHERE parent_session_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSubagentSessionsByParent(ctx context.Context, parentSessionID pgtype.UUID) ([]BotSession, error) {
	rows, err := q.db.Query(ctx, listSubagentSessionsByParent, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSession
	for rows.Next() {
		var i BotSession
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.RouteID,
			&i.ChannelType,
			&i.Type,
			&i.SessionMode,
			&i.RuntimeType,
			&i.RuntimeMetadata,
			&i.Title,
			&i.Metadata,
			&i.NextTurnPosition,
			&i.ParentSessionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionNextTurnPosition = `-- name: SetSessionNextTurnPosition :exec
UPDATE bot_sessions
SET next_turn_position = $1::bigint
WHERE id = $2
`

type SetSessionNextTurnPositionParams struct {
	NextTurnPosition int64       `json:"next_turn_position"`
	SessionID        pgtype.UUID `json:"session_id"`
}

func (q *Queries) SetSessionNextTurnPosition(ctx context.Context, arg SetSessionNextTurnPositionParams) error {
	_, err := q.db.Exec(ctx, setSessionNextTurnPosition, arg.NextTurnPosition, arg.SessionID)
	return err
}

const softDeleteSession = `-- name: SoftDeleteSession :exec
UPDATE bot_sessions
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSession, id)
	return err
}

const softDeleteSessionsByBot = `-- name: SoftDeleteSessionsByBot :exec
UPDATE bot_sessions
SET deleted_at = now(), updated_at = now()
WHERE bot_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSessionsByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSessionsByBot, botID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE bot_sessions
SET updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateSessionMetadata = `-- name: UpdateSessionMetadata :one
UPDATE bot_sessions
SET metadata = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateSessionMetadataParams struct {
	Metadata []byte      `json:"metadata"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSessionMetadata(ctx context.Context, arg UpdateSessionMetadataParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionMetadata, arg.Metadata, arg.ID)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :one
UPDATE bot_sessions
SET title = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateSessionTitleParams struct {
	Title string      `json:"title"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionTitle, arg.Title, arg.ID)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSessionTypeAndMetadata = `-- name: UpdateSessionTypeAndMetadata :one
UPDATE bot_sessions
SET type = $1,
    session_mode = $2,
    runtime_type = $3,
    runtime_metadata = $4,
    metadata = $5,
    updated_at = now()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, bot_id, route_id, channel_type, type, session_mode, runtime_type, runtime_metadata, title, metadata, next_turn_position, parent_session_id, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateSessionTypeAndMetadataParams struct {
	Type            string      `json:"type"`
	SessionMode     string      `json:"session_mode"`
	RuntimeType     string      `json:"runtime_type"`
	RuntimeMetadata []byte      `json:"runtime_metadata"`
	Metadata        []byte      `json:"metadata"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSessionTypeAndMetadata(ctx context.Context, arg UpdateSessionTypeAndMetadataParams) (BotSession, error) {
	row := q.db.QueryRow(ctx, updateSessionTypeAndMetadata,
		arg.Type,
		arg.SessionMode,
		arg.RuntimeType,
		arg.RuntimeMetadata,
		arg.Metadata,
		arg.ID,
	)
	var i BotSession
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.RouteID,
		&i.ChannelType,
		&i.Type,
		&i.SessionMode,
		&i.RuntimeType,
		&i.RuntimeMetadata,
		&i.Title,
		&i.Metadata,
		&i.NextTurnPosition,
		&i.ParentSessionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSessionDiscussCursor = `-- name: UpsertSessionDiscussCursor :one
INSERT INTO bot_session_discuss_cursors (
  session_id, scope_key, route_id, source, consumed_cursor
)
VALUES (
  $1,
  $2,
  $3::uuid,
  $4,
  $5
)
ON CONFLICT (session_id, scope_key) DO UPDATE
SET route_id = COALESCE(EXCLUDED.route_id, bot_session_discuss_cursors.route_id),
    source = EXCLUDED.source,
    consumed_cursor = GREATEST(bot_session_discuss_cursors.consumed_cursor, EXCLUDED.consumed_cursor),
    updated_at = now()
RETURNING session_id, scope_key, route_id, source, consumed_cursor, updated_at
`

type UpsertSessionDiscussCursorParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	ScopeKey       string      `json:"scope_key"`
	RouteID        pgtype.UUID `json:"route_id"`
	Source         string      `json:"source"`
	ConsumedCursor int64       `json:"consumed_cursor"`
}

func (q *Queries) UpsertSessionDiscussCursor(ctx context.Context, arg UpsertSessionDiscussCursorParams) (BotSessionDiscussCursor, error) {
	row := q.db.QueryRow(ctx, upsertSessionDiscussCursor,
		arg.SessionID,
		arg.ScopeKey,
		arg.RouteID,
		arg.Source,
		arg.ConsumedCursor,
	)
	var i BotSessionDiscussCursor
	err := row.Scan(
		&i.SessionID,
		&i.ScopeKey,
		&i.RouteID,
		&i.Source,
		&i.ConsumedCursor,
		&i.UpdatedAt,
	)
	return i, err
}
