// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSnapshotByContainerAndRuntimeName = `-- name: GetSnapshotByContainerAndRuntimeName :one
SELECT snapshots.id, snapshots.container_id, snapshots.runtime_snapshot_name, snapshots.display_name, snapshots.parent_runtime_snapshot_name, snapshots.snapshotter, snapshots.source, snapshots.created_at, snapshots.team_id
FROM snapshots
JOIN containers c ON c.container_id = snapshots.container_id
WHERE snapshots.container_id = $1
  AND snapshots.runtime_snapshot_name = $2
  AND c.team_id = $3
LIMIT 1
`

type GetSnapshotByContainerAndRuntimeNameParams struct {
	ContainerID         string      `json:"container_id"`
	RuntimeSnapshotName string      `json:"runtime_snapshot_name"`
	TeamID              pgtype.UUID `json:"team_id"`
}

func (q *Queries) GetSnapshotByContainerAndRuntimeName(ctx context.Context, arg GetSnapshotByContainerAndRuntimeNameParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByContainerAndRuntimeName, arg.ContainerID, arg.RuntimeSnapshotName, arg.TeamID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.RuntimeSnapshotName,
		&i.DisplayName,
		&i.ParentRuntimeSnapshotName,
		&i.Snapshotter,
		&i.Source,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const listSnapshotsByContainerID = `-- name: ListSnapshotsByContainerID :many
SELECT snapshots.id, snapshots.container_id, snapshots.runtime_snapshot_name, snapshots.display_name, snapshots.parent_runtime_snapshot_name, snapshots.snapshotter, snapshots.source, snapshots.created_at, snapshots.team_id
FROM snapshots
JOIN containers c ON c.container_id = snapshots.container_id
WHERE snapshots.container_id = $1
  AND c.team_id = $2
ORDER BY snapshots.created_at DESC
`

type ListSnapshotsByContainerIDParams struct {
	ContainerID string      `json:"container_id"`
	TeamID      pgtype.UUID `json:"team_id"`
}

func (q *Queries) ListSnapshotsByContainerID(ctx context.Context, arg ListSnapshotsByContainerIDParams) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByContainerID, arg.ContainerID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.ContainerID,
			&i.RuntimeSnapshotName,
			&i.DisplayName,
			&i.ParentRuntimeSnapshotName,
			&i.Snapshotter,
			&i.Source,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsWithVersionByContainerID = `-- name: ListSnapshotsWithVersionByContainerID :many
SELECT
  s.id,
  s.container_id,
  s.runtime_snapshot_name,
  s.display_name,
  s.parent_runtime_snapshot_name,
  s.snapshotter,
  s.source,
  s.created_at,
  cv.version
FROM snapshots s
LEFT JOIN container_versions cv ON cv.snapshot_id = s.id
JOIN containers c ON c.container_id = s.container_id
WHERE s.container_id = $1
  AND c.team_id = $2
ORDER BY s.created_at DESC
`

type ListSnapshotsWithVersionByContainerIDParams struct {
	ContainerID string      `json:"container_id"`
	TeamID      pgtype.UUID `json:"team_id"`
}

type ListSnapshotsWithVersionByContainerIDRow struct {
	ID                        pgtype.UUID        `json:"id"`
	ContainerID               string             `json:"container_id"`
	RuntimeSnapshotName       string             `json:"runtime_snapshot_name"`
	DisplayName               pgtype.Text        `json:"display_name"`
	ParentRuntimeSnapshotName pgtype.Text        `json:"parent_runtime_snapshot_name"`
	Snapshotter               string             `json:"snapshotter"`
	Source                    string             `json:"source"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	Version                   pgtype.Int4        `json:"version"`
}

func (q *Queries) ListSnapshotsWithVersionByContainerID(ctx context.Context, arg ListSnapshotsWithVersionByContainerIDParams) ([]ListSnapshotsWithVersionByContainerIDRow, error) {
	rows, err := q.db.Query(ctx, listSnapshotsWithVersionByContainerID, arg.ContainerID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSnapshotsWithVersionByContainerIDRow
	for rows.Next() {
		var i ListSnapshotsWithVersionByContainerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ContainerID,
			&i.RuntimeSnapshotName,
			&i.DisplayName,
			&i.ParentRuntimeSnapshotName,
			&i.Snapshotter,
			&i.Source,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSnapshot = `-- name: UpsertSnapshot :one
INSERT INTO snapshots (
  container_id,
  team_id,
  runtime_snapshot_name,
  display_name,
  parent_runtime_snapshot_name,
  snapshotter,
  source
)
SELECT
  c.container_id,
  c.team_id,
  $1,
  $2,
  $3,
  $4,
  $5
FROM containers c
WHERE c.container_id = $6
  AND c.team_id = $7
ON CONFLICT (container_id, runtime_snapshot_name) DO UPDATE
SET
  display_name = EXCLUDED.display_name,
  parent_runtime_snapshot_name = EXCLUDED.parent_runtime_snapshot_name,
  snapshotter = EXCLUDED.snapshotter,
  source = EXCLUDED.source
WHERE EXISTS (
  SELECT 1
  FROM containers c
  WHERE c.container_id = snapshots.container_id
    AND c.team_id = $7
)
RETURNING id, container_id, runtime_snapshot_name, display_name, parent_runtime_snapshot_name, snapshotter, source, created_at, team_id
`

type UpsertSnapshotParams struct {
	RuntimeSnapshotName       string      `json:"runtime_snapshot_name"`
	DisplayName               pgtype.Text `json:"display_name"`
	ParentRuntimeSnapshotName pgtype.Text `json:"parent_runtime_snapshot_name"`
	Snapshotter               string      `json:"snapshotter"`
	Source                    string      `json:"source"`
	ContainerID               string      `json:"container_id"`
	TeamID                    pgtype.UUID `json:"team_id"`
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, upsertSnapshot,
		arg.RuntimeSnapshotName,
		arg.DisplayName,
		arg.ParentRuntimeSnapshotName,
		arg.Snapshotter,
		arg.Source,
		arg.ContainerID,
		arg.TeamID,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ContainerID,
		&i.RuntimeSnapshotName,
		&i.DisplayName,
		&i.ParentRuntimeSnapshotName,
		&i.Snapshotter,
		&i.Source,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}
