services:
  postgres:
    image: memoh.cn/library/postgres:18-alpine
  qdrant:
    image: memoh.cn/qdrant/qdrant:latest
  migrate:
    image: memoh.cn/memohai/server:latest
  server:
    image: memoh.cn/memohai/server:latest
  web:
    image: memoh.cn/memohai/web:latest
  browser:
    image: memoh.cn/memohai/browser:latest
  browser-chromium:
    image: memoh.cn/memohai/browser-chromium:latest
  browser-firefox:
    image: memoh.cn/memohai/browser-firefox:latest