services:
  postgres:
    image: memoh.cn/library/postgres:18-alpine
  pgvector:
    image: memoh.cn/pgvector/pgvector:pg18
  migrate:
    image: memoh.cn/memohai/server:latest
  server:
    image: memoh.cn/memohai/server:latest
  web:
    image: memoh.cn/memohai/web:latest
