package acpclient

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"path"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/memohai/memoh/internal/workspace/bridge"
)

const (
	codexAgentID                    = "codex"
	codexManagedAPIKeyProviderID    = "OpenAI"
	codexManagedAPIKeyProviderName  = "OpenAI"
	codexManagedOAuthProviderID     = "chatgpt-http"
	codexManagedOAuthProviderName   = "ChatGPT HTTP"
	codexDefaultOpenAIBaseURL       = "https://api.openai.com/v1"
	codexDefaultChatGPTCodexBaseURL = "https://chatgpt.com/backend-api/codex"
	codexManagedConfigTemplate      = `# Generated by Memoh for managed Codex ACP sessions.
model_provider = {{ tomlString .ProviderID }}
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
model_supports_reasoning_summaries = true
hide_agent_reasoning = false
show_raw_agent_reasoning = false

[model_providers.{{ .ProviderID }}]
name = {{ tomlString .ProviderName }}
base_url = {{ tomlString .BaseURL }}
wire_api = "responses"
requires_openai_auth = {{ .RequiresOpenAIAuth }}
supports_websockets = false
`
)

// CodexManagedConfigDir is the standard Codex config directory inside the
// managed container workspace.
const CodexManagedConfigDir = dataMountPath + "/.codex"

var codexConfigTemplate = template.Must(template.New("codex-managed-config").
	Funcs(template.FuncMap{"tomlString": strconv.Quote}).
	Parse(codexManagedConfigTemplate))

type codexManagedConfigData struct {
	ProviderID         string
	ProviderName       string
	BaseURL            string
	RequiresOpenAIAuth bool
}

type CodexManagedConfig struct {
	Mode    SetupMode
	Managed map[string]string
	OAuth   *CodexOAuthCredentials
}

type CodexOAuthCredentials struct {
	AccessToken  string //nolint:gosec // runtime credential material used to construct Codex auth.json
	IDToken      string
	RefreshToken string //nolint:gosec // runtime credential material used to construct Codex auth.json
	AccountID    string
	BaseURL      string
	ExpiresAt    time.Time
	LastRefresh  time.Time
}

// WriteCodexManagedConfig writes the fixed Codex config.toml and auth.json
// used by Memoh-managed Codex ACP sessions.
func WriteCodexManagedConfig(ctx context.Context, client *bridge.Client, managed map[string]string) error {
	return WriteCodexManagedConfigWithAuth(ctx, client, CodexManagedConfig{
		Mode:    SetupModeAPIKey,
		Managed: managed,
	})
}

func WriteCodexManagedConfigWithAuth(ctx context.Context, client *bridge.Client, cfg CodexManagedConfig) error {
	if client == nil {
		return errors.New("workspace bridge client is required")
	}
	auth, err := renderCodexManagedAuth(cfg)
	if err != nil {
		return fmt.Errorf("render Codex auth: %w", err)
	}
	content, err := renderCodexManagedConfig(cfg)
	if err != nil {
		return fmt.Errorf("render Codex config: %w", err)
	}
	if err := client.WriteFile(ctx, path.Join(CodexManagedConfigDir, "config.toml"), content); err != nil {
		return fmt.Errorf("write Codex config: %w", err)
	}
	if err := client.WriteFile(ctx, path.Join(CodexManagedConfigDir, "auth.json"), auth); err != nil {
		return fmt.Errorf("write Codex auth: %w", err)
	}
	return nil
}

func renderCodexManagedConfig(cfg CodexManagedConfig) ([]byte, error) {
	data := codexManagedConfigData{
		ProviderID:   codexManagedAPIKeyProviderID,
		ProviderName: codexManagedAPIKeyProviderName,
		BaseURL:      strings.TrimSpace(cfg.Managed["base_url"]),
	}
	switch normalizeSetupMode(cfg.Mode) {
	case SetupModeOAuth:
		data.ProviderID = codexManagedOAuthProviderID
		data.ProviderName = codexManagedOAuthProviderName
		data.BaseURL = codexOAuthProviderBaseURL(cfg.OAuth)
		data.RequiresOpenAIAuth = true
	default:
		if data.BaseURL == "" {
			data.BaseURL = codexDefaultOpenAIBaseURL
		}
	}

	var out bytes.Buffer
	if err := codexConfigTemplate.Execute(&out, data); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

func codexOAuthProviderBaseURL(creds *CodexOAuthCredentials) string {
	if creds == nil {
		return codexDefaultChatGPTCodexBaseURL
	}
	baseURL := strings.TrimRight(strings.TrimSpace(creds.BaseURL), "/")
	if baseURL == "" {
		return codexDefaultChatGPTCodexBaseURL
	}
	if strings.HasSuffix(baseURL, "/codex") {
		return baseURL
	}
	if strings.HasSuffix(baseURL, "/backend-api") {
		return baseURL + "/codex"
	}
	return baseURL
}

func renderCodexManagedAuth(cfg CodexManagedConfig) ([]byte, error) {
	switch normalizeSetupMode(cfg.Mode) {
	case SetupModeOAuth:
		return renderCodexManagedOAuthAuth(cfg.OAuth)
	default:
		return renderCodexManagedAPIKeyAuth(cfg.Managed)
	}
}

func renderCodexManagedAPIKeyAuth(managed map[string]string) ([]byte, error) {
	apiKey := strings.TrimSpace(managed["api_key"])
	if apiKey == "" {
		return nil, errors.New("api_key is required")
	}
	content, err := json.MarshalIndent(map[string]string{
		"OPENAI_API_KEY": apiKey,
	}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(content, '\n'), nil
}

func renderCodexManagedOAuthAuth(creds *CodexOAuthCredentials) ([]byte, error) {
	if creds == nil {
		return nil, errors.New("oauth credentials are required")
	}
	accessToken := strings.TrimSpace(creds.AccessToken)
	if accessToken == "" {
		return nil, errors.New("oauth access token is required")
	}
	idToken := strings.TrimSpace(creds.IDToken)
	if idToken == "" {
		return nil, errors.New("oauth id token is required")
	}
	accountID := strings.TrimSpace(creds.AccountID)
	if accountID == "" {
		return nil, errors.New("oauth account id is required")
	}
	lastRefresh := creds.LastRefresh
	if lastRefresh.IsZero() {
		lastRefresh = time.Now().UTC()
	}
	content, err := json.MarshalIndent(map[string]any{
		"auth_mode": "chatgpt",
		"tokens": map[string]string{
			"id_token":      idToken,
			"access_token":  accessToken,
			"refresh_token": strings.TrimSpace(creds.RefreshToken),
			"account_id":    accountID,
		},
		"last_refresh": lastRefresh.UTC().Format(time.RFC3339Nano),
	}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(content, '\n'), nil
}

func isCodexAgent(agentID string) bool {
	return strings.EqualFold(strings.TrimSpace(agentID), codexAgentID)
}
