// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const countMemoryNodeEmbeddings = `-- name: CountMemoryNodeEmbeddings :one
SELECT COUNT(*)
FROM public.memory_node_embeddings
WHERE bot_id = $1
  AND model_id = $2
`

type CountMemoryNodeEmbeddingsParams struct {
	BotID   pgtype.UUID `json:"bot_id"`
	ModelID pgtype.UUID `json:"model_id"`
}

func (q *Queries) CountMemoryNodeEmbeddings(ctx context.Context, arg CountMemoryNodeEmbeddingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoryNodeEmbeddings, arg.BotID, arg.ModelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBotMemoryNodeEmbeddings = `-- name: DeleteBotMemoryNodeEmbeddings :exec
DELETE FROM public.memory_node_embeddings
WHERE bot_id = $1
`

func (q *Queries) DeleteBotMemoryNodeEmbeddings(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotMemoryNodeEmbeddings, botID)
	return err
}

const deleteMemoryNodeEmbeddings = `-- name: DeleteMemoryNodeEmbeddings :exec
DELETE FROM public.memory_node_embeddings
WHERE bot_id = $1
  AND node_id = ANY($2::text[])
`

type DeleteMemoryNodeEmbeddingsParams struct {
	BotID   pgtype.UUID `json:"bot_id"`
	NodeIds []string    `json:"node_ids"`
}

func (q *Queries) DeleteMemoryNodeEmbeddings(ctx context.Context, arg DeleteMemoryNodeEmbeddingsParams) error {
	_, err := q.db.Exec(ctx, deleteMemoryNodeEmbeddings, arg.BotID, arg.NodeIds)
	return err
}

const memoryNodeEmbeddingsExist = `-- name: MemoryNodeEmbeddingsExist :one
SELECT EXISTS (
  SELECT 1
  FROM public.memory_node_embeddings
  LIMIT 1
)
`

func (q *Queries) MemoryNodeEmbeddingsExist(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, memoryNodeEmbeddingsExist)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchMemoryNodeEmbeddings = `-- name: SearchMemoryNodeEmbeddings :many
SELECT
  node_id,
  CAST(1.0 - (embedding <=> $1::vector) AS double precision) AS score
FROM public.memory_node_embeddings
WHERE bot_id = $2
  AND model_id = $3
ORDER BY embedding <=> $1::vector
LIMIT $4
`

type SearchMemoryNodeEmbeddingsParams struct {
	Embedding pgvector_go.Vector `json:"embedding"`
	BotID     pgtype.UUID        `json:"bot_id"`
	ModelID   pgtype.UUID        `json:"model_id"`
	RowLimit  int32              `json:"row_limit"`
}

type SearchMemoryNodeEmbeddingsRow struct {
	NodeID string  `json:"node_id"`
	Score  float64 `json:"score"`
}

func (q *Queries) SearchMemoryNodeEmbeddings(ctx context.Context, arg SearchMemoryNodeEmbeddingsParams) ([]SearchMemoryNodeEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, searchMemoryNodeEmbeddings,
		arg.Embedding,
		arg.BotID,
		arg.ModelID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoryNodeEmbeddingsRow
	for rows.Next() {
		var i SearchMemoryNodeEmbeddingsRow
		if err := rows.Scan(&i.NodeID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemoryNodeEmbedding = `-- name: UpsertMemoryNodeEmbedding :exec
INSERT INTO public.memory_node_embeddings (
  bot_id, node_id, model_id, dimensions, body_hash, embedding
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (bot_id, node_id, model_id) DO UPDATE SET
  dimensions = EXCLUDED.dimensions,
  body_hash = EXCLUDED.body_hash,
  embedding = EXCLUDED.embedding,
  updated_at = now()
`

type UpsertMemoryNodeEmbeddingParams struct {
	BotID      pgtype.UUID        `json:"bot_id"`
	NodeID     string             `json:"node_id"`
	ModelID    pgtype.UUID        `json:"model_id"`
	Dimensions int32              `json:"dimensions"`
	BodyHash   string             `json:"body_hash"`
	Embedding  pgvector_go.Vector `json:"embedding"`
}

func (q *Queries) UpsertMemoryNodeEmbedding(ctx context.Context, arg UpsertMemoryNodeEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertMemoryNodeEmbedding,
		arg.BotID,
		arg.NodeID,
		arg.ModelID,
		arg.Dimensions,
		arg.BodyHash,
		arg.Embedding,
	)
	return err
}
