#!/usr/bin/env sh

export PATH="$HOME/.local/share/mise/shims:$HOME/.local/bin:$HOME/.npm-global/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

echo "Check frontend lint..."
pnpm lint:fix || true

echo "Check building ..."
pnpm web:build
